### ISSUE TITLE
Handle Paragliding rating

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#1110]
https://forum.camptocamp.org/t/parapente-mise-au-point-de-lechelle-de-cotation/259456/50

It has been decided to use only 1 rating for paragliding.

**Comment by cbeauchesne** [comment]
Draft of a spec here : https://forum.camptocamp.org/t/parapente-mise-au-point-de-lechelle-de-cotation/259456/53?u=charlesb

**Comment by cbeauchesne** [comment]
Too much hack to be done oonly on UI side, we need to make an API modification (add new field, and rename the other one).

**Comment by cbeauchesne** [comment]
After further discussion, use the same property for both waypoint type, rename values, and limit to 4 levels : https://forum.camptocamp.org/t/parapente-mise-au-point-de-lechelle-de-cotation/259456/68?u=charlesb

**Comment by cbeauchesne** [comment]
Done. The limitation of the scale to [1-4] will be done on API side : v6_api#817
