### ISSUE TITLE
Feature: save layer choosen by user

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1126]
When a user change map layer, save his choice.

TBD on forum

**Comment by asaunier** [comment]
Is it really relevent?

For instance if you looked at a topo in Switzerland and selected the Swisstopo baselayer, you don't need to have this baselayer loaded by default when you look later at topo in France.

In addition, as the Swisstopo baselayer has a quota and costs a lot of money, it's a bit a waste to load Swisstopo tiles if the user is not really interested to see them.

**Comment by AntoineMarnat** [comment]
It is a problem if the user choose a map that is not worldwide.

**Comment by cbeauchesne** [comment]
We discussed about this point with the board, as an alternative to show IGN map by default (this layer will be free in few years). And as IGN does not cover the world, save the user choice could have been an idea.

 > In addition, as the Swisstopo baselayer has a quota and costs a lot of money, it's a bit a waste to load Swisstopo tiles if the user is not really interested to see them.

Definitly a good point, thank's a lot

**Comment by brunobesson** [comment]
I also disagree on this point.

**Comment by cbeauchesne** [comment]
Yep, I also do not agree, because of alex remark, but also because I think opentopomap is the best solution (open source ...).

I'll raise our concern to the board, and close the issue if they agree.

**Comment by asaunier** [comment]
By the way, the selected baselayer already remains the same for all pages browsed during a session. It's set back to the default layer only when closing/reopening a browser window.
Which means we already have the problem of the Swisstopo tiles used for maps displayed after the user has enabled them once.

**Comment by cbeauchesne** [comment]
Yep.

We finally agree to keep it as is. thank you for your help !
