### ISSUE TITLE
Feature: add visual infobox while mouse flyover icons on the MAP

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#1129]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/reunion-du-06-05-2020-odj-et-ca/259818/10

**Is your feature request related to a problem? Please describe.**
users do not know how change the map source and sometimes do not know it is possible !

**Describe the solution you'd like**
add information and visual event to help users find out the way to change map source and map size (ENLARGE) while fly over noth icons.

**Comment by brunobesson** [comment]
This is a board restricted discussion on the forum.

However, there is already a title on map controls, just not on our custom ones, i.e. the layer switch.

**But**, it happens I made such corrections to add title on layer switcher and add translations for other controls recently. It is already committed on master and should be delivered for the next release.

Job's already done :) The only difference with what you suggest is that it's an HTML title, which means it will appears after 1s or so, not immediatly. But this would be a bad UX behaviour anyway, so I do think the current solution is OK. You can test it on the demo: https://c2corg.github.io/c2c_ui/master/#/

**Comment by brunobesson** [comment]
Maybe some translations could be reconsidered, e.g. `Couches` for layer switcher.

**Comment by cbeauchesne** [comment]
> But, it happens I made such corrections to add title on layer switcher and add translations for other controls recently. It is already committed on master and should be delivered for the next release.

Confirmed, my bad, I did not seen the title attribute
