### ISSUE TITLE
Bug: PR builds are brokken

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1142]
On https://c2corg.github.io/c2c_ui/fix-mtb-unit/ : 

![image](https://user-images.githubusercontent.com/11915659/81537115-fc7ca680-936c-11ea-89b8-999d353887e5.png)

`undefined` should have been branch name

The line to fix is here : https://github.com/c2corg/c2c_ui/blob/master/vue.config.js#L132

**Comment by brunobesson** [comment]
oops

**Comment by brunobesson** [comment]
@cbeauchesne once I merge the PR, you can rebase yours and it should work properly.
