### ISSUE TITLE
To be discussed : remove docker image build on push on master

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1148]
As we use github pages for demoing (including master), building docker image on each push to master is a waste of time and ressource. And actually, we never used it since the first release of this UI. I suggest to remove it, and only build it for release. 

@brunobesson , your opinion ?

**Comment by brunobesson** [comment]
I do not agree.
It makes sense to have a latest release that reflects the state of the art on master. We do not use the demo server a lot, but in such case it is sometimes pertinent to use the latest tag. Could be used by some dev too.

As for resources, this tag is overridden each tile, so the cost in only something like 30mb. Which is nothing compared to the tags that were published for each branch before I migrated to GitHub actions ;-) (I removed those manually)

**Comment by cbeauchesne** [comment]
Ok, thank you!

**Comment by brunobesson** [comment]
@cbeauchesne by the way, I was wondering how we could enhance the size of the github pages branch. We accumulate branches, and they are never cleand up. I thought about removing files, but the history would remain, we would then need to overwrite the branch history.
What do you think?

**Comment by cbeauchesne** [comment]
@brunobesson,  As now, I manually remove old builds (approx every 6 month). important point, I like the fact that we always keep available old versions of the prod, in case of any doubt/debate about how it **was**.

If we have a algo that determine which folder can be safely deleted, ok for me. I would say : 

* Not master
* AND not a release (`^\d+\.\d+\.\d+` pattern)
* AND PR closed
* AND unchanged for 2 months

Then we can delete the folder

Just, to compute the utility function, it takes 5 minutes each 6 month to do it manually ;)

**Comment by brunobesson** [comment]
>  I manually remove old builds (approx every 6 month)

Yeah, but as I said, it keeps everything in the history, so you've got your waste of resources, almost as big as docker images. Rewriting history would be the only solution IMHO

> Old versions of the prod

this is the whole purpose of the docker images for vX.Y.Z, isn't it?

> `^\d+\.\d+\.\d+`

Should be rather `^v\d+\.\d+\.\d+`

**Comment by cbeauchesne** [comment]
> Yeah, but as I said, it keeps everything in the history, so you've got your waste of resources, almost as big as docker images. Rewriting history would be the only solution IMHO

The waste of ressource I was talking was about docker image computation: build&push docker takes half of the CI time when we commit on master. On that point, you're perfectly right as it takes some time for github to push large folders to github pages.

> this is the whole purpose of the docker images for vX.Y.Z, isn't it?

Nope, I want to keep them available live and running without any manual step. The purpose for this is multiple : easy way for devs to check how it was, and a **living** proof of the past if there is any debate on community. 

> Should be rather `^v\d+\.\d+\.\d+`

yep !

**Comment by brunobesson** [comment]
> Nope, I want to keep them available live and running without any manual step.

But this won't work as soon as we introduce some breaking changes on the API side, e.g. SERAC modifications. Then one the simplest way to do it is to use docker (compose)

**Comment by cbeauchesne** [comment]
Yep, an infra repo with docker-compose command ready to fire will be the golden target for rock solid repro. But for the casual need, even with some buggy parts (which happen very rarely, in 3 years, it's the first time we make a breaking change on API), it worths to keep them working.

I used them several times to check when some details changed, and it was possible to do this with one click. And docker isn't even a subject for other people.

With a cost a single regexp, and a dozen of second on CI, anybody can perform this check (did i miss some cost? correct me if I'm totally wrong), the ratio added-value/cost seems unbeatable to me. And at least way cheaper than images generated by merges on master that has never been used.
