### ISSUE TITLE
Fix box shadow

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1149]
Bulma was updated from 0.7.5 to 0.8.2

It comes with a modification of box shadows : https://github.com/jgthms/bulma/commit/43b4b0bdc3139cf9c68f1a4ec604eed40b6d4c1e#diff-b5269e4512a3320cf8759fe9490361b1

Even if I personnaly like the new style, it's not coherent with other part of the UI  (and touching the design should be discussed with community) : 

From : 
![image](https://user-images.githubusercontent.com/11915659/81661392-58fac700-943c-11ea-89ec-1d9b161f1d46.png)

To: 
![image](https://user-images.githubusercontent.com/11915659/81661490-7760c280-943c-11ea-8fcc-916d46263930.png)

Old style : 

``` scss
$box-shadow: rgba(10, 10, 10, 0.1) 0px 2px 3px 0px, rgba(10, 10, 10, 0.1) 0px 0px 0px 1px;
```

**Comment by brunobesson** [comment]
I did a check when upgrading the lib, I missed this point, sorry.

As for implicating the community, true, but for such a minor point I do think it is a bit useless. Well, if you have the will for this, I won't prevent you from it :)

**Comment by cbeauchesne** [comment]
Definitly not the will to start a discussion for this shadow, I'll only set it to the old value :)
