### ISSUE TITLE
Feature: rename button "Continue the discussion" when too many comments in a document

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#1157]
**Describe the bug**

When more than N comments are posted in documents, only the first N comments are displayed in the document footer.
Visitors may read the other comments in Discourse by pressing the "Continue the discussion" button but it's not explicit enough that only a subset of comments are shown

**To Reproduce**
1. Go to https://www.camptocamp.org/outings/1195132/fr/journal-d-un-confinement-epilogue-adiou-adichat => only 19 comments are shown
2. Click on button "Continue the discussion", leading to https://forum.camptocamp.org/t/1195132-fr/258246/104 => 104 comments (and counting)

**Expected behavior**

Add an indicator making it obvious that more comments are available if nb comments > N (19?). Eg. adding a comment counter. Or renaming the button,

**Comment by brunobesson** [comment]
Seems to be limited (by default) to 19 first comments.
