### ISSUE TITLE
Bug: forum sidebar display error

### ISSUE THREAD

**Issue by hemind** [c2corg/c2c_ui#1187]
I have got such sidebar display error in the forum page for some days. I have reproduced this error on chrome for mac version 83.0.4103.61, firefox, and safari.

![image](https://user-images.githubusercontent.com/7596172/83030551-f3a9f700-a033-11ea-842a-2548396b79ba.png)

**Comment by brunobesson** [comment]
I assume there is no chinese translation for discourse? Or it is not installed? @fbunoz is the one mainly working on this part.

**Comment by hemind** [comment]
Hello @brunobesson , there is [chinese translation](https://www.transifex.com/discourse/discourse-org/) for discourse. And above display error is always presented no matter what language I choose in the preferences.
