### ISSUE TITLE
Bug: map recenter do not work for Chinese UI

### ISSUE THREAD

**Issue by hemind** [c2corg/c2c_ui#1188]
For English version, if I type some word in the blank, it shows a list of place which I can choose to recenter. But for Chinese version, it does not show anything. See pics below.

English UI
![image](https://user-images.githubusercontent.com/7596172/83034404-7e8cf080-a038-11ea-92be-df2c83cf2faf.png)

Chinese UI
![image](https://user-images.githubusercontent.com/7596172/83034813-f3f8c100-a038-11ea-9aec-2472e216fe72.png)

**Comment by brunobesson** [comment]
I had a look at it, it's an easy fix we will include soon.

**Comment by hemind** [comment]
Great! Thanks a lot.
