### ISSUE TITLE
Design differences on fresh install

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#1233]
It seems that there are "bugs" with Bulma 0.9.0. Many helpers aren't loaded.

After cloning the repo, installing deps, and running it, some design problems appears, as in TopoGuide page (class `is-flex` is missing)

![image](https://user-images.githubusercontent.com/1260529/84907234-3e5ae400-b0b3-11ea-9a62-795d2aabf9a9.png)

After small researches, it seems that Bulma moved some required files. As an example, loading `@import '~bulma/sass/helpers/_all.sass';` fixed the `is-flex`, but other differences are still noticeable (like the sizes of buttons on the top right corner)

Website
![image](https://user-images.githubusercontent.com/1260529/84907440-7bbf7180-b0b3-11ea-9982-4892a7466b17.png)

Cloned one
![image](https://user-images.githubusercontent.com/1260529/84907467-84b04300-b0b3-11ea-8385-5b5dd1cd48c1.png)

Any clue on that?

**Comment by brunobesson** [comment]
I am certainly responsible for this. I tested the upgrade lightly, mainly fixed an import change and had a quick look a the rendering which seemed fine. But maybe I wasn't precautious enough. In such a case, we should revert my PR for upgrade while we still have to investiguate the upgrade.

**Comment by brunobesson** [comment]
Made a PR to fix everything I found!
