### ISSUE TITLE
Enhancement: border consistency

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#1266]
Currently, it looks like the choice has been made to:
* use sharp edges for boxes in view mode (see feed boxes, or document views boxes)
* use round edges in edition mode (see inputs, markdown editor).

However, association card have sharp edges, not rounded one, which make it inconsistent. This should be fixed. Either by adding round corners to it, or sharpening everything.

@cbeauchesne what did you have in mind?

**Comment by brunobesson** [comment]
I made a simple PR to use rounded borders.

**Comment by cbeauchesne** [comment]
> @cbeauchesne what did you have in mind?

Nothing really intended here, I guess I'm not the best UI designer :)

Just, for the PR, I suggest using Bulma helper class and variable when they exists, it'll be far easier for the maintenance => `$radius` here (doc is here https://bulma.io/documentation/customize/variables/)

**Comment by brunobesson** [comment]
> I suggest using Bulma helper class and variable when they exists

Sure I totally agree with that, but when I looked, I saw so many hard-coded values that I thought it wasn't used so I had no will to rework all. Will use `$radius` in this case 👍
