### ISSUE TITLE
Bug: paragliding quotation from P1-P4 only - Remove P5 choice in  WP take off field

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#1292]
**Describe the bug**
Dans l’ articles cotations atterro et déco il est déterminé une échelle de P1 à P4 mais lorsque l’on rentre un nouveau WP déco ou atterro, dans la rubrique « Cotation » il y a une échelle de P1 à P5 dans le menu déroulant.
Il faudrait modifier cette rubrique afin de n’afficher que de P1 à P4.

https://forum.camptocamp.org/t/parapente-mise-au-point-de-lechelle-de-cotation/259456/72

**Comment by lbesson** [comment]
- [ ] Make sure that no waypoint is currently using P5 rating (https://www.camptocamp.org/waypoints?pgrat=5)

- [ ] Change the UI to only allow P1 - P4

**Comment by brunobesson** [comment]
As for the P5 entry in the translation tool, see my comment on PR, there is nothing to do once it is merged.
