### ISSUE TITLE
Bug: XREPORT document - Double "Autres blessures" choice

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#1332]
**Describe the bug**
Dans le formulaire de rapport di'ncident il y a un double hoix "autres blessures" dans la partir "blessure antérieures"
voir screencshot
https://www.camptocamp.org/xreports/add/fr

Voir si ce choix est désiré !
![Sans titre](https://user-images.githubusercontent.com/49275256/89709107-387bd380-d97d-11ea-9d50-893cf90f5f26.png)

**Comment by brunobesson** [comment]
@cbeauchesne why was it closed? fixed? not relevant? fixedwith translations? I could need to update extract tool too

**Comment by cbeauchesne** [comment]
Fixed by #1375 no ?

**Comment by brunobesson** [comment]
I had missed it, sorry.
