### ISSUE TITLE
Wiki: Improve i18n documentation 

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#1443]
Hello,

I find current documentation for i18n lacking some informations. Could you elaborate a bit on this?

What I understand:

- Add `v-translate`, `$gettext` inside code where appropriate
- keys will be automatically created based on text
- then a github action will upload keys to transifex and a PR will be created

Can you confirm this first?

Things that are missing/questions:

- Texts have to be in english in code?
- How/where/when to set translations in other languages?
- How to deal with long block of texts (and containing HTML elements)? (eg, the faq on the yeti page)
- Is there a way to set own keys, not based on text?
- How duplicate keys are handled?
- What do you mean by "If you need to specify a translation context to translators, use translate-context attribute"? What is context? At what point it is helpful?
- Is it possible/required to organize all keys for a specific route/page (like `/yeti` for example)?

Thanks!

**Comment by cbeauchesne** [comment]
Hi @iamvdo ,

I've completed the wiki. Short answers: 

> Texts have to be in english in code?

yes

> How/where/when to set translations in other languages?

Here : https://www.transifex.com/camptocamp-association/

> How to deal with long block of texts (and containing HTML elements)? (eg, the faq on the yeti page)

Transifex system does not works with formatted text. For this use case, you can use an article. It's not as easy, but not too hard though. I can help you on this.

> Is there a way to set own keys, not based on text?

Nope.

> How duplicate keys are handled?
> What do you mean by "If you need to specify a translation context to translators, use translate-context attribute"? What is context? At what point it is helpful?

Same answer for those two questions. The context helps translator to give the good translation. And is there is duplicate keys (synonyms or contextualized) that should not be translated equally, the context is here to remove any ambiguity

> Is it possible/required to organize all keys for a specific route/page (like /yeti for example)?

No, the translation is valid trough the entire app.

**Comment by iamvdo** [comment]
>Transifex system does not works with formatted text. For this use case, you can use an article. It's not as easy, but not too hard though. I can help you on this.

For long texts, I find it not that hard to use articles. But what about smaller texts? Like few words? Should I also create an article? (It seems a bit overkill, and not very convenient when you have many chunks of text to translate)

**Comment by cbeauchesne** [comment]
Yep, do not create an article for short text, it's definitly overkill.

If you can separate it in many chunks, do it. But it's sometimes not possible, as the translation can change the order.  In this case, use this: 

```html
    <!-- eslint-disable-next-line vue/no-v-html -->
    <span v-html="$gettext('<strong>a bold test</strong> close to an <em>emphatized</em> text')"></span>
```

It need to be an exception (I did not documented this on purpose :smiley: ). The comment is here to disable lint check, as `v-html` directive can lead to an XSS attack and has been forbidden in this repo (but exceptions are allowed)

**Comment by iamvdo** [comment]
Thank you! 
Is that means that you *can* create keys with html content? 

The point is I have component with slots, so `v-html` won't work as-is. But I get it, so I will no longer use slots I think :)

Another question: how about dynamic texts? Like "There is N things", where N is dynamic. Translations can change order too (maybe not in that specific case though)

**Comment by cbeauchesne** [comment]
> Is that means that you can create keys with html content?

With great powers comes great responsibilities :) 

> The point is I have component with slots, so v-html won't work as-is. But I get it, so I will no longer use slots I think :)

I do not have solution here. The `v-html` is the only hack I've supported, as our site does not contains a lot of statics texts.

 > Another question: how about dynamic texts? Like "There is N things", where N is dynamic. Translations can change order too (maybe not in that specific case though)

Another point I did not coded. The exchange format between our source code and transifex is `.pot` (more info here https://www.gnu.org/software/gettext/manual/gettext.html) and it supports dynamic values. But we'll need to adapt our code to support it > https://github.com/c2corg/c2c_ui/blob/master/tools/extract-messages.js

**Comment by iamvdo** [comment]
Thanks for all the explanations. 

I noticed a weird bug, not sure how it's related. When using `v-translate` and `v-if`, it doesn't seem to work, even if nested.

See for yourself:

This works as expected
```vue
<p v-if="model">hello</p>
<p v-else>world</p>
```

Adding `v-translate`, and `v-if` no longer works
```vue
<p v-if="model" v-translate>hello</p>
<p v-else v-translate>world</p>
```

Even with nested
```vue
<p v-if="model"><span v-translate>hello</span></p>
<p v-else><span v-translate>world</span></p>
```

**Comment by cbeauchesne** [comment]
Seems to be a vue limitation, if I remember well, the framework is not able to determine the good DOM elements in certain use case when we use the same tag. It explains why we need to use a `key` with `v-for`.

It work with two different tags, as the frameworks got a way to remove know which one is the good node. 

I would say that it should be possible to fix it on our side, as I can't see a good reason to this behaviour specifically on `v-if` where other UI logic works perfectly without `key`, but the point is that `key` may fix the issue. You can try this:  

```html
    <span v-if="model" key="id_1" v-translate>hello</span>
    <span v-else  key="id_2" v-translate>world</span>
```

**Comment by cbeauchesne** [comment]
For the record, the code that handle this part is here : 

https://github.com/c2corg/c2c_ui/blob/master/src/js/vue-plugins/gettext-plugin.js

It's by far the deeper "vue.js" code I've wrote, so I'm not really confortable to touch this :/

**Comment by brunobesson** [comment]
There a plugins to handle this, e.g. vue-i18n, which Charles didn't know of when he rewrote the UI. But this would require quite some work to switch,  not mentioning the 'context' that Charles added for c2c.

**Comment by iamvdo** [comment]
I'm not here to add extra work to anyone :) Actual solution is great, I'm just questioning edge cases I found, in case proper solutions exist.

Thanks for the `key` solution!

**Comment by iamvdo** [comment]
Last question, about translating messages from API.

So, messages have to be written in code blocks, but how to tell which text to translate? (examples no longer use `v-translate`) Is it automatically what is next line ?

**Comment by cbeauchesne** [comment]
I'm not sure to understand what you mean, sorry . Maybe a example can help me understand?

**Comment by iamvdo** [comment]
Using

```vue
<template>
    <!-- $gettext('an API message') -->
    <span></span>
</template>
```

How i18n know which text to translate? Does it translates `"An API message"` only in next `<span>`, or no matter where the text is found?

**Comment by cbeauchesne** [comment]
On your example : 

* `An API message` will be sent to transifex
* and as you noticed, vue can't know where to put the message, so nothing will be rendered

If you want to use translation without `v-translate` : 

```html
<span v-text="$gettext('The is no reason to use this instead of v-translate, it's just an example')" />
``` 

```html
<span v-html="$gettext('I really really want to add <b>translated</b> HTML, I've no choice but using v-html')" />
```

**Comment by iamvdo** [comment]
I don't want to use translation without `v-translate`, that's the point. But your example do not use `v-translate`. That's why I'm consued.

I want to write something like this:

```
<template>
    <!-- $gettext('an API message') -->
    <span v-translate>{{ messageFromApi }}</span>
</template>
```

It is how it should be used?

**Comment by cbeauchesne** [comment]
But the point is that `v-translate` and  `$gettext` are two differents way of using i18n, each serving one usage, and without intersection in both usage.

* `v-translate` is used only for simple texts contents that can be directly hard-coded in pure HTML code. It the most basic use case (and the most common one)
* `$gettext`  is only used for more complex use case:
  * The source text cannot be placed in `<template>` section: [example](https://github.com/c2corg/c2c_ui/blob/bd64d06c1ad6129df36b71fc7bf7c6b158430eb5/src/js/waypoint-labels-mixin.js#L24)  
  * The source text does not exists in UI source code: [we copy paste it from API source in a comment](https://github.com/c2corg/c2c_ui/blob/bd64d06c1ad6129df36b71fc7bf7c6b158430eb5/src/views/user/utils/FormField.vue#L7) 
  * the translated text must be sent threw an attribute: https://github.com/c2corg/c2c_ui/blob/d811bda88bb31546ca44a966f55a7635a032037e/src/views/document/utils/boxes/ToolBox.vue#L20
  * you need to make a transformation on translated text : https://github.com/c2corg/c2c_ui/blob/bb88806b937a16ee848aa4dff3b48371e5a64085/src/views/documents/utils/QueryItem.vue#L23
  * or your translated text can contains v-html : https://github.com/c2corg/c2c_ui/blob/472437ca9a24c83dc11f1efd978f49de8e226198/src/components/images-uploader/ImagesUploader.vue#L40 

in a word: `v-translate` for the most common (and very simple) use case, `$gettext` otherwise.

**Comment by iamvdo** [comment]
OK, so as far as I understand, my last example should be:

```vue
<template>
    <!-- $gettext('an API message') -->
    <span>{{ $gettext(messageFromApi) }}</span>
</template>
```

Right?

**Comment by cbeauchesne** [comment]
yes, if messageFromApi is in `data` object of your component:

```js
export default {
  data() {
    return {
      messageFromApi: someApi.getMessage(),  // this function may return 'an API message' 
    }
  }
}
```

**Comment by iamvdo** [comment]
Well, API returns object with many messages. It is more something like:

```vue
<template>
    <!-- $gettext('an API message') -->
    <!-- $gettext('another API message') -->
    <span v-for="message in messagesFromApi">{{ $gettext(message) }}</span>
</template>

<script>
export default {
  data() {
    return {
      messagesFromApi: someApi.getMessages(),
    }
  }
}
</script>
```

Is it working?

**Comment by cbeauchesne** [comment]
Yep, just do not forget the `key` attribute with the `v-for`  :)

**Comment by iamvdo** [comment]
OK, thanks! 👍
