### ISSUE TITLE
Feature: encourage filling history of a route for apropriate activity

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#1505]
Camptocamp is aiming to have the best information about the history of routes - and very good at it. I suggest the following to be even better

**Describe the solution you'd like**
For the following activities: snow_ice_mixed, mountain_climbing, rock_climbing, ice_climbing, via_ferrata, slacklining
If the history field is empty, instead of hiding it, show it with the text " You know the history of the route ? Fill it in ! " as a link to the edition page, open at the history section.

It follows the behavior for cotation, see:
https://www.camptocamp.org/routes/1261111/

If technically no too tricky, one could also add skitouring under the condition that the cotation is higher than 5.1:  trat=5.1,5.6

**Comment by asaunier** [comment]
> If the history field is empty, instead of hiding it, show it with the text " You know the history of the route ? Fill it in ! " as a link to the edition page, open at the history section.

Should not be displayed when printing

**Comment by AntoineMarnat** [comment]
Hello,

I would be happy to try to give it a go, but I would need some help. In particular, I am not familiar at all with the tree of the different files.

As far as I understand, the changes must be done in this file:
https://github.com/c2corg/c2c_ui/blob/master/src/views/document/RouteView.vue
Example of the rating : lines 27-29:

> <label-value :label="$gettext('ratings')">
>                 <document-rating v-if="$documentUtils.hasRating(document)" :document="document" show-helper />
>                 <edit-link v-else :document="document" :lang="$user.lang" />

and changing line 80

>          <markdown-section :document="document" :field="fields.route_history" />

Unfortunatly, I can't find where "hasRating" is defined ... If someone can hint me where the printing setup is ?

**Comment by brunobesson** [comment]
Hi. The `hasRating` function is defined in `src\js\vue-plugins\document-utils.js`. It is developped as a Vue plugin which adds a global property `$documentUtils`, which you can thus access with `this` keyword.

What you need to do then:
* either display the `MarkdownSection` component if route history is filled or deosn't match your criteria, otherwise display another component which will present your text
* or customize the `MarkdownSection` component to handle specific cases.

Which one is best depends on the complexity and structure of the modifications, but I assume it will be best to modify the component.

**Comment by cbeauchesne** [comment]
It may be something like transforming 

https://github.com/c2corg/c2c_ui/blob/master/src/views/document/RouteView.vue#L80

```html 
<markdown-section :document="document" :field="fields.route_history" />
```

into 

```html 
<markdown-section v-if="locale.route_history" :document="document" :field="fields.route_history" />
<div v-else class="missing-history-banner" v-translate/> Missing history, lorem ipsum</div>
```

Side note: thee `locale` property is a variable pointing directly to the good locale object.

**Comment by AntoineMarnat** [comment]
Thanks for the tips, I am working on it at the moment. Looking where 'edit-link' is defined. I was doing something like what Charles suggests.

**Comment by brunobesson** [comment]
> It may be something like transforming (...)

As far as I read the issue description, it cannot be as simple as this, because this message should only appear in some cases, not everytime there is no history filled.

> pointing directly to the good locale object.
But $cooked$
