### ISSUE TITLE
Find a good tooltip lib

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#155]
Requirements :

* [ ] Light
* [ ] fast
* [ ] works on all elements
  * [ ] CSS overflow:hidden
* [ ] when element is close to window borders : if tooltip area is outside, it must autaticly be replaced on a visible location, or at least not change page size (ugly scroll bar poping effect)
* [ ] good v-tooltip or v-title integration (it's easy to do this on our own)

Tested : 

* bulma-tooltip 
  * does not work inside a overflow:hidden 
  * if tooltip is close to parent element border, it may cause a scrollbar blink

**Comment by flob38** [comment]
Don't know if this one has all requirements but it seems to me that it's replaced automatically.
And I don't no either if it can work with our "configuration"...
http://qtip2.com/

**Comment by brunobesson** [comment]
jquery -> throw away 😭
