### ISSUE TITLE
Show an error message when an editing conflict occurs

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#1564]
When editing a document, if someone has saved changes in the meantime, the API refuses to save the pushed changes and returns a 409 error.
The UI does not handle this conflict error : nothing happens, one may press the "save" button again but the changes are not saved and it's not clear why saving does not work.

Expected behaviour: at least show an error message explaining why changes cannot be changed and what the user should do.

**Comment by brunobesson** [comment]
Actually the message is displayed, but on the top of the document.
I'll submit a PR to rework those messages using toast.
