### ISSUE TITLE
Bug: Impossible to remove route distance

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1572]
**Describe the bug**
Impossible to remove route distance

**To Reproduce**
1. Go to https://www.camptocamp.org/routes/336870/fr/pointe-de-pierre-fendue-face-sw
2. The route distance is 0
3. Edit the document to clear the field
4. Nothing is changed

**Expected behavior**
Field shoudl be resetted

**Comment by brunobesson** [comment]
Here also, the field seems to have been reset?
Is this bug reproducible?

**Comment by lbesson** [comment]
https://www.camptocamp.org/routes/diff/336870/fr/prev/2418391

Yes, might have been some cache issue too?

**Comment by lbesson** [comment]
I tested on demo, and the pb didn't seem to exist
