### ISSUE TITLE
Bug: Images icon not always displayed

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1577]
**Describe the bug**
A clear and concise description of what the bug is. Français autorisé, deutsch erlaubt, autorizzato italiano

**To Reproduce**
1. Go to https://www.camptocamp.org/routes/50479/fr/montagne-d-outray-croix-versant-nw
2. The outing 02-01-2020 has no image icon, despit the outing having images linked

**Expected behavior**
We should have both the gps + images icon

**Screenshots**
https://www.camptocamp.org/routes/50479/fr/montagne-d-outray-croix-versant-nw
![image](https://user-images.githubusercontent.com/127776/103797319-9e61a980-5048-11eb-94eb-f2ed807d8d93.png)

**Comment by brunobesson** [comment]
I cannot reproduce. May it be a problem of indexation / cache (either on the frontend or API side)?

**Comment by lbesson** [comment]
You're probably right.
