### ISSUE TITLE
Bug: raw url not active in the topoguide

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#1583]
See https://forum.camptocamp.org/t/url-nue-inactive-dans-le-topoguide/273085

**Comment by ataraxido** [comment]
@AntoineMarnat seems the page you linked isn't available for everyone : "Oups ! Cette page n'existe pas ou est privée."

**Comment by AntoineMarnat** [comment]
Indeed, it's on the private forum for association members:

> Bubu
> 2 j
> 
> Depuis peu, les urls nue sont inactives dans le topoguide (itinéraires, sorties, articles).
> Du coup, par exemple cet article est devenu inutilisable, à moins de copier-coller les url à la main dans la barre d’adresse, ou d’avoir une extension qui active les liens, mais elles sont obsolètes régulièrement (sur Firefox, l’extension à tout faire « Tab-mix + » ne fonctionne plus depuis un moment) : Camptocamp.org 4
> 
> Idem pour de nombreux itinéraires, dans le champ « ressources externes ».
> Il est bien sûr préférable de mettre le lien sur du texte, mais il n’y a aucune raison de pénaliser un contributeur qui prend le temps de mettre un lien, fusse-t-il nu. D’autres contributeurs pourront ajouter du texte. C’est l’amélioration progressive du contenu comme pour le reste.
> Dans le forum les liens sont activés automatiquement, avec même le titre de la page mis automatiquement comme texte du lien. Là c’est propre et ergonomique.
> Par ailleurs, inutile de me répondre qu’il suffit d’ajouter des balises. Il n’y a aucune valeur ajoutée à mettre des balises sur un lien nu juste pour l’activer (sans y mettre de texte). C’est juste chiant et anti-ergonomique, et presque personne ne le fait, car tout le monde est habitué à ce qu’un lien nu soit automatiquement activé.
> 
> Pourquoi l’activation automatique des liens a été désactivée ?



> CharlesB
> 
> Nope, c’est voulu. Le code qui gérait cela était « fait maison », et gérait très mal pas mal de cas (example dans ce bug remonté par @Loic_P : Double parsing of links when label is like an URL · Issue #27 · c2corg/c2c_markdown · GitHub 1).
> 
> Faire cette détection automatiquement proprement est assez subtil, et je suis totalement à court de temps, j’ai préféré désactiver l’extension.
> 
> A noter que la façon « officielle » de faire un lien en markdown est d’encadrer l’URL avec des chevrons :
> 
> <https://forum.camptocamp.org/t/url-nue-inactive-dans-le-topoguide/273085/2>
