### ISSUE TITLE
Bug: Incorrect dates formatting in dashboard

### ISSUE THREAD

**Issue by naspert** [c2corg/c2c_ui#1632]
Since commit bf738a3ae75c8769852daefc08d72561fd4185c1, date formatting is now done by date-fns library. However the format string specifier 'do' is buggy for the french language (cf. https://github.com/date-fns/date-fns/issues/437).
This result in awkward looking dates in the dashboard when French language is used.
<img width="671" alt="Screenshot 2021-01-28 at 14 40 08" src="https://user-images.githubusercontent.com/1047452/106169579-cf3c8680-618f-11eb-8064-9fb988134aa9.png">

**Comment by naspert** [comment]
Change is located here : https://github.com/c2corg/c2c_ui/commit/bf738a3ae75c8769852daefc08d72561fd4185c1#diff-2a39ba3c34ff38c2f6420b3e055b3fe9469d1681c2d32977ebbc49b27433f693

**Comment by brunobesson** [comment]
Forgot to check that one. It's the problem when noone does a review 🙁 
I'll fix it shortly.
