### ISSUE TITLE
Small UI glitches on list view

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1642]
On this screenshot : 

![image](https://user-images.githubusercontent.com/11915659/106719463-a1799680-6602-11eb-9592-509a7de5f65d.png)

* The button `export to csv` should be smaller
* a margin is missing between this button and the "bauges" label
* Also, IMO, we should use a different layout for these two items
* the quality and GPS flag are truncated on list

**Comment by brunobesson** [comment]
Indeed, I missed the areas filtering when I coded, I never use it.
