### ISSUE TITLE
Support HEIF images metadata

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#1699]
Current lib https://github.com/blueimp/JavaScript-Load-Image doesn't support HEIF metadata (https://github.com/blueimp/JavaScript-Load-Image/issues/117).
There may be an alternative lib for this listed in the issue, to be investigated.

**Comment by brunobesson** [comment]
Example file: https://drive.google.com/file/d/1IZ6S0vejKIlLFvplQ_bfwhQQ30mjxRl_/view?usp=sharing

**Comment by laurentenhoor** [comment]
Hi @brunobesson, are you working on this? Do you need any help?

**Comment by brunobesson** [comment]
Hi @laurentenhoor 
No this is kind of stale. I made the work to handle parsing metadata, however there is no support for heif images in most browser as of yet, so it is kind of useless.

What do you have in mind?

**Comment by laurentenhoor** [comment]
I just need it to default to another format like jpg or png.

**Comment by brunobesson** [comment]
If you are willing to work on this subject, please do, you are welcome to do so!
Should you need any help / advice, feel free to write at dev@camptocamp.org
