### ISSUE TITLE
Feature: Best period display on climbing site

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1749]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/indication-des-mois/276888

**Is your feature request related to a problem? Please describe.**
Useless verbose display when the climbing period include all months.

**Describe the solution you'd like**
Display "full year" instead of list of 12 months

**Describe alternatives you've considered**
Nothing, quite straghtforward solution

**Additional context**
NA

**Exemple**
https://www.camptocamp.org/waypoints/895474/fr/saint-restitut-secteur-de-la-poudriere

**Comment by brunobesson** [comment]
As I have done something similar for biodivsport, I'll handle this
