### ISSUE TITLE
Feature: move down the toolbox on mobile

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#1756]
**Community discussion about this feature (mandatory)**
Can't remember when, it's been a while

**Is your feature request related to a problem? Please describe.**
On mobile, document view is inherited from the desktop view, without any logic. The result is :

1. title
1. map
1. toolbox
1. figures
1. textual descriptions
1. outings, routes
1. forum

Which is not so bad, except for toolbox

**Describe the solution you'd like**
Toolbox between textual descriptions and associated docs, or between associated docs and forum

**Describe alternatives you've considered**
Do nothing

**Comment by brunobesson** [comment]
Quite easy to solve with flex order, isn't it?

**Comment by cbeauchesne** [comment]
There is a plugin `$screen` that expose relevant property. I can do it easily with that way (it's done one articleView that way).

Flex box would be definitly more elegant, but will probably ask more work (at least for me :) )

**Comment by brunobesson** [comment]
One could even think of using grid layout in order to handle this and more stuff (now that we do not support IE anymore)

**Comment by brunobesson** [comment]
Not that easy in the end... but doable.
