### ISSUE TITLE
Bug: Association between images should be bidirectionnal

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1806]
**Describe the bug**
If you associate two images, the associated image is only displayed on the parent (or child - I don't know exactly 😄) page

**To Reproduce**
https://www.camptocamp.org/images/1302955/fr/col-d-albanne-versant-nw-et-pointe-d-emy-couloir-n
https://www.camptocamp.org/images/1302835/fr/vue-generale-du-couloir

**Expected behavior**
The linked images should be displayed on both pages

**Additional context**
I do think this is a pure UI issue, but maybe this is also an API issue

**Comment by brunobesson** [comment]
This is in fact an API issue...

**Comment by brunobesson** [comment]
I have created https://github.com/c2corg/v6_api/issues/1032
