### ISSUE TITLE
Bug: Next/previous buttons in the photo gallery disappear after 4s even when using them

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#1844]
**Describe the bug**
A recent upgrade made buttons of the image gallery disappear after 4s when the mouse cursor is not moving (I think).
A non-critical side effect is that when a user browses images in the gallery by clicking on the "next" or "previous" arrows (thus not moving the cursor), after a few seconds the arrows disappear, hence can no longer be clicked to move to the next image. One has to move the cursor again to get the buttons back and be able to keep clicking on the arrows :P 

**Expected behavior**
Perhaps keep the arrows anyway when the cursor is not moving?

**Comment by lbesson** [comment]
@brunobesson

**Comment by brunobesson** [comment]
I reproduced the bahavior from previous tool we used, swiperjs which I like a lot. You can always move with arrow keys. Should you use the mouse, then it appears again as soon as you move.
But apparently this is counter intuitive to you ..

**Comment by lbesson** [comment]
we could still detect user clicked on the button and mouse didn't move since (yes it's a bit cumbersome)

**Comment by asaunier** [comment]
@brunobesson This not intuitive: you're clicking on the "next" arrow, browsing the images and all of a sudden clicking no longer shows the next image (you may think you're at the end of the gallery) until you realize the arrow has disappeared and that it appears again when you move the mouse.

**Comment by brunobesson** [comment]
Ok, I'll have a look at it. Could you make a quick test with https://photoswipe.com/ though? This is the implementation I referred to, not swiperjs (which is the tool we are currently using)

**Comment by brunobesson** [comment]
I quit, you win @asaunier :)
