### ISSUE TITLE
Feature: Do not use lodash debounce package

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1894]
See https://lodash.com/per-method-packages

We shouldn't use "lodash.debounce", but rather lodash with tree shaking

**Comment by brunobesson** [comment]
The current build is smaller with lodash.debounce.

![image](https://user-images.githubusercontent.com/2234024/117466056-9bbd8500-af52-11eb-93c6-ea2582cf969e.png)
vs
![image](https://user-images.githubusercontent.com/2234024/117465994-89dbe200-af52-11eb-8cf5-97baf447cbb1.png)

But when using only this, we should instead event use vanilla debounce method. I'll make a PR, we'll save another extra kb 🙂

**Comment by lbesson** [comment]
I guess we badly shake tree (or don't at all)
