### ISSUE TITLE
Optimise space used for personalized feed configuration

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#1925]
The current display of the configuration for personal field takes too much place on some narrow devices.

![image](https://user-images.githubusercontent.com/2234024/118713607-6ce0c200-b822-11eb-8845-9e7db6326dc1.png)

There may be some ways to enhance this.

**Comment by brunobesson** [comment]
Some proposals (to be enhanced sometimes):

* Menu with ellipsis button
  
![image](https://user-images.githubusercontent.com/2234024/118713772-9ef22400-b822-11eb-9cd8-06eb6e1b4e0c.png)
![image](https://user-images.githubusercontent.com/2234024/118713795-a6193200-b822-11eb-8751-21caa4e092f2.png)

* Simple button with 2 states
 
![image](https://user-images.githubusercontent.com/2234024/118714460-e11b6580-b822-11eb-8ced-56346d203052.png)
![image](https://user-images.githubusercontent.com/2234024/118714566-e7114680-b822-11eb-912d-f276922e42c6.png)

* Switch
![image](https://user-images.githubusercontent.com/2234024/118714730-05774200-b823-11eb-803e-8c252d8071b2.png)

* Shorten text?

**Comment by lbesson** [comment]
Likevth switch, more comprehensible than current control imho

**Comment by cbeauchesne** [comment]
> Like the switch, more comprehensible than current control imho

Same

**Comment by asaunier** [comment]
I would keep some text to make the tool more explicit.
Perhaps simply updating the translation from "Fil personnel activé" to "Fil personnel" would do the job? (a bit like your proposal "Personnaliser")

By the way, is there also a problem with the card headers, stuck to the left (see the first screenshot)?

**Comment by brunobesson** [comment]
> By the way, is there also a problem with the card headers, stuck to the left (see the first screenshot)?

Only because there isn't enough space to place both the title and the configuration on the same line.
