### ISSUE TITLE
Bug: Outing document quality field lost when edited

### ISSUE THREAD

**Issue by ataraxido** [c2corg/c2c_ui#1959]
When editing an outing, the (even if locked) document quality field value is lost : the field value comes back to draft or void whereas it hasn't been edited.

**Comment by cbeauchesne** [comment]
It's on purpose, this field is meant to be (almost) always computed, and the UI is designed in that way.
If you edit an outing where computed quality is different to actuel quality, it'll be overridden if you do nothing.
To keep the "manually chosen" quality you need to click on the lock.

More detail about the rationnals here : https://forum.camptocamp.org/t/completude-preparation-du-vote/252317

**Comment by ataraxido** [comment]
I think there's however an issue , see https://forum.camptocamp.org/t/bug-affichage-liaison-entre-itineraire-et-sortie-sur-plusieurs-itineraires/281299/2
