### ISSUE TITLE
Bug: Virtual waypoints shouldn't be on the minimap

### ISSUE THREAD

**Issue by lbesson** [c2corg/c2c_ui#1970]
**Describe the bug**
Virtual waypoints shouldn't be on the minimap.
Unless maybe it's the only waypoint and there is no geometry attached (gpx..)

**To Reproduce**
Example https://www.camptocamp.org/routes/107202/fr/foret-de-fontainebleau-circuit-des-25-bosses
![image](https://user-images.githubusercontent.com/127776/120193697-0180f200-c21d-11eb-8608-9f4ee806d2af.png)

**Comment by AntoineMarnat** [comment]
Agreed !
