### ISSUE TITLE
Feature: filter outings by date, independently from the year

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#1979]
**Community discussion about this feature (mandatory)**
Among other: https://forum.camptocamp.org/t/recherche-par-date-independamment-de-lannee/281329

**Is your feature request related to a problem? Please describe.**
It would be a great feature to check if a route is usualy in condition on a given period of the year.

**Describe the solution you'd like**
When filtering by date, have the same behaviour than now when you provide full date (with year ), and a new behaviour by not filling the year.

It probably requires API modification ?

**Comment by cbeauchesne** [comment]
> It probably requires API modification ?

Yes :)
