### ISSUE TITLE
Feature: Disclaimer for empty and draft documents

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#1984]
The aim of this feature is to  emphasis the fact that camptocamp is a collaborative and contributive wiki. 

The idea, following Wikipedia (see for example [here](https://fr.wikipedia.org/wiki/Aphidol%C3%A8te) ), is to add a disclaimer for documents (waypoints, routes, areas, articles, books, but not outings or images) when the completness/quality is either 'empty' or 'draft'.

The disclaimer should be like:

"This document is a draft/empty, feel free to [edit the document] (link to edit page) to provide information and improve its quality"

**Comment by brunobesson** [comment]
My proposal add the disclaimer only for routes and collaborative articles. I assume there would be too many cases for other documents such as waypoints and areas. Maybe book could work, but is it meaningfull?
