### ISSUE TITLE
Hide single point geometry on route view

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#1992]
Viewing a route point geometry is kind of disturbing for 'normal' users: there is absolutely no interest in it, on the contrary it adds noise to the map, particularly if there are many associated waypoints, notwithstanding a track. So the idea is to hide point geometry for routes. This geometry should still be visible when editing, of course.

The only negative impact I see is that for those working on fixing and placing such point geometry appropriately, you can't just view the document and see if corrections are needed.

**Comment by cbeauchesne** [comment]
I'm not sure to understand, it means that the route geoloc will always be hidden when you have a trace ?

**Comment by brunobesson** [comment]
> I'm not sure to understand, it means that the route geoloc will always be hidden when you have a trace ?

Nope. If you look at #1995 
* for routes view, always hide point geometry
* for outings view, hide point geometry if track is available

The second point is more controversial, but I am pretty convinced for this first one.

The idea is that this point geometry has no use when you are viewing a single route document (in opposition with a list of routes  map). You have the other important waypoints, you may have the track. But the point geometry doesn't bring anything in this case IMHO.

**Comment by cbeauchesne** [comment]
I'm not really sure that for route it's really relevant : 

* For "climbing" routes, the point is located at the begnining of difficulties, it's very very useful (not saying a must-have)
* For non-climbing site (ski touring, hiking...), the value is less clear, but we have rules on how to place it: https://www.camptocamp.org/articles/107007/fr/aide-topoguide-cartographie-georeferencements
* And some contributors made a huge effort past few years to locate precisely lot of routes

Or did I missed something ?

**Comment by brunobesson** [comment]
I do agree the placement of the single point geometry is extremely important. For lists. I do not want to remove them. Only hide them when they are not pertinent.

Meije ridges traverse:
![image](https://user-images.githubusercontent.com/2234024/121035231-f7776a00-c7ad-11eb-8f4c-33d28b8c1e0c.png)
Rouies SW:
![image](https://user-images.githubusercontent.com/2234024/121035333-0eb65780-c7ae-11eb-848f-c753b857f85a.png)
Whats the use of the point geometry there? It only blurs the map.

As for the "climbing routes" (which by the way exclude most "alpine" climbs), what you are suggesting is only a workaround to having a detailed geometry...

To be discussed, however... 🤕

**Comment by cbeauchesne** [comment]
The Meije traverse is a good counter-example : it should have been placed at the beginning of the route : the refuge terrace :D 

For instance, on this one : https://www.camptocamp.org/routes/55942/fr/aiguille-de-la-republique-voie-normale
=> The trace includes the most common approach, and the point is located at the very beginning of the route itself.

**Comment by brunobesson** [comment]
> The Meije traverse is a good counter-example : it should have been placed at the beginning of the route : the refuge terrace :D

So it's useless. CQFD

> For instance, on this one : https://www.camptocamp.org/routes/55942/fr/aiguille-de-la-republique-voie-normale

I'm not convinced, sorry. This is partly in contradiction with the need to use this to render on the map. On "long" routes, you don't want to se the point at the begining of the difficulties. E.g. https://www.camptocamp.org/routes/54093/fr/olan-arete-n The point is misplaced currently (should IMHO be at 1/3 f the ridge). But not at the start of the climb anyway.

**Comment by cbeauchesne** [comment]
> So it's useless. CQFD

For the Meije traverse, yes, but it's an exception, as the start of the route is the most obvious start in all french alps.

>  On "long" routes, you don't want to se the point at the begining of the difficulties

It's not my opinion. For lot of routes, finding the start can be very tricky, and having the map with precise geoloc can be a huge help. If we have a way to safely determine which routes it's useless, and which routes it's useful, why not. But removing the point for all routes is a big regression IMO.

And actually, it's what's applied for a while, the actual rule is described [here](https://www.camptocamp.org/articles/107007/fr/aide-topoguide-cartographie-georeferencements) : 

> * Pour les itinéraires grimpants (alpinisme, cascade, grande voie, couenne), la géolocalisation est placée à l'attaque de l'itinéraire
> * Pour les itinéraires non grimpants en aller-retour, le point doit être au début de la partie non commune avec d'autres itinéraires. Le but est que :
>   * les itinéraires d'un sommets ne soient pas affichées groupés à 50 m du sommet
>   * les itinéraires d'un vallon ne soient pas affichées groupées à un endroit du fond de vallon
> * Pour un itinéraire en traversée mais dont la descente ne constitue pas les difficultés, le point est placé sur l'itinéraire de montée, à un endroit discriminant. Quand il y a un autre itinéraire qui emprunte la même montée, on éloigne un peu les 2 points.

We definitely cannot change the interface with such an impact on an accepted rule without discussing on the forum.

**Comment by AntoineMarnat** [comment]
> For lot of routes, finding the start can be very tricky, and having the map with precise geoloc can be a huge help. If we have a way to safely determine which routes it's useless, and which routes it's useful, why not. But hiding this point for all routes with a trace is a big regression IMO.
> 
> And actually, it's what's applied for a while, the actual rule is described [here](https://www.camptocamp.org/articles/107007/fr/aide-topoguide-cartographie-georeferencements) :
> 
> > * Pour les itinéraires grimpants (alpinisme, cascade, grande voie, couenne), la géolocalisation est placée à l'attaque de l'itinéraire
> > * Pour les itinéraires non grimpants en aller-retour, le point doit être au début de la partie non commune avec d'autres itinéraires. Le but est que :
> >   
> >   * les itinéraires d'un sommets ne soient pas affichées groupés à 50 m du sommet
> >   * les itinéraires d'un vallon ne soient pas affichées groupées à un endroit du fond de vallon
> > * Pour un itinéraire en traversée mais dont la descente ne constitue pas les difficultés, le point est placé sur l'itinéraire de montée, à un endroit discriminant. Quand il y a un autre itinéraire qui emprunte la même montée, on éloigne un peu les 2 points.
> 
> We definitely cannot change the interface with such an impact on an accepted rule without discussing on the forum.

I completly agree with that.
Yes, for many routes the georef is not well placed. Yes for T1 hiking it is probably not relevant. But it was asked many times for climbing/mountaineering routes, and can be relevant for some hiking routes as well. Hiding it in general is thus a regression, and we should rather work on making contributors placing them correctly.
