### ISSUE TITLE
Bug: The search tool is not working properly

### ISSUE THREAD

**Issue by guidup** [c2corg/c2c_ui#1996]
**Describe the bug**
The search engine misses quite often results that can be found by other means (Google...). 

**To Reproduce**

1. Go to https://www.camptocamp.org/waypoints/102686/fr/saint-peray-top-secret-crussol-
2. Go to https://www.camptocamp.org/routes?bbox=535534,5607025,545580,5615570&act=rock_climbing
3. See that the first topo is nowhere in the search of the second link

**Expected behavior**
The search engine misses most of the results

**Desktop (please complete the following information):**

Chrome on Windows 10

**Comment by cbeauchesne** [comment]
Hi @guidup ,

Thank's for your report.

Actually, your second URL is looking for routes only `/routes' . If you use `/waypoints`, you'll find the document : 

https://www.camptocamp.org/waypoints?bbox=530222,5600509,550194,5623127

Or did I missed something ?

**Comment by guidup** [comment]
I understand that. 
Why is there a distinction between the 2 ?
Especially for climbing, I feel some spots are classified as waypoints, some as routes... how about multipitches, are they points or routes ?

**Comment by cbeauchesne** [comment]
A waypoint can be a lot of thing : https://github.com/c2corg/c2c_ui/blob/master/src/js/constants/common.json#L298-L323

In particular, it can be a climbing site (`climbing_outdoor`), where will be attached several routes. And routes can be attached to any kind of waypoint, most of the time, `climbing_outdoor` waypoint are for crag sites, or very dense multipitch sites.

**Comment by guidup** [comment]
Then maybe it is a wider question about not about how to classify but rather how to access the data. 
When I am looking for an ideas for an outing, I feel either to go to outings for conditions or just new ideas, or i know the specifications of what I am looking for I I go to the topoguide and what in a single search to access climbing, via ferattas and other routes... It should be on one side the topos for activities and on another the waypoints that can be used in the topos for references (such as summits, huts, sources...)

**Comment by cbeauchesne** [comment]
I'm not sure to see that is your proposition. but I feel it's more functional than technical, am I right ? 

If yes, it's very welcome (as we, power users, may miss a lot of ergonomic issue), do you mind starting a discussion on the forum? we trying to not make any functional discussion on GH, as we need  

https://forum.camptocamp.org/c/site-et-association/site-c2c-suggestions-bugs-et-problemes (or https://forum.camptocamp.org/c/english/news-events if you don't speak french).
