### ISSUE TITLE
Feature: better date range for pictures

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2002]
**Is your feature request related to a problem? Please describe.**
For old pictures/painting, it would be good to go earlier than the actual limit of 1st january 1970.

e.g.:
https://www.camptocamp.org/images/1213989
https://www.camptocamp.org/images/817565

**Describe the solution you'd like**
According to https://www.camptocamp.org/articles/1204368
it may be relevant to set january 1700 as the limit.

It would also be interesting to be able to set only the year, and not day and time.

**Comment by brunobesson** [comment]
? There is no such limit. I could update both images date.

**Comment by AntoineMarnat** [comment]
Strange, I have an error `document.date_time: Invalide date`

With FF 86.0.1

**Comment by brunobesson** [comment]
Indeed. But it's rather the date format which is invalid:

![image](https://user-images.githubusercontent.com/2234024/121350509-12bbb400-c92b-11eb-8179-7eba50a3c7ef.png)

It should be something like `1900-01-01T00:01:27+00:09` instead
While it's ok with Chrome. I also see a strange behavior when selecting minutes...

So there is definitely a bug, although it's not what you described 🙂

**Comment by brunobesson** [comment]
Okay then, it's a bit more complicated (google why there is 9 mintues and eleven seconds offset with UTC in 1900 if you like), but in the end it's a date-fns bug, because it assume `Date.getTimezoneOffset` returns an integer value, which Chrom does, but not Firefox.

**Comment by brunobesson** [comment]
I reported the issue there: https://github.com/date-fns/date-fns/issues/2509
