### ISSUE TITLE
Bug: margin is too big on documents

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#2038]
![image](https://user-images.githubusercontent.com/11915659/122999422-8db2af00-d3ae-11eb-89cf-caeeacbcf9e4.png)

vs 

![image](https://user-images.githubusercontent.com/11915659/122999490-a02ce880-d3ae-11eb-90e6-c88beb2b9cf1.png)

https://www.camptocamp.org/outings?qa=draft,great&bbox=-431698,3115462,1931123,8442818
https://c2corg.github.io/c2c_ui/sort-ui/#/outings?qa=draft,great&bbox=-1418091,3119850,2917516,8438430

**Comment by brunobesson** [comment]
Must be caused by bulma update.
I read the [changelog](https://github.com/jgthms/bulma/blob/master/CHANGELOG.md), thought there would be no impact, but in fact the `New $section-padding-desktop Sass variable` must have an impact, it is defined at 3rem instead of .75rem we used up to now.
