### ISSUE TITLE
Technical advice on using OLMap or not

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#2059]
I'm currently working on YETI again, adding new features to the map. I'm facing technical problems and need some advice.

Until now, the `YetiMap` component uses the `OLMap` one as-is. It gives us advantages (basically, same map on YETI than whole website and no need to write similar code twice), but has drawbacks (comes with unwanted features (like filtering) and it's sometimes hard to add new features and leads to more code).

For example, when added drawing capabilities on the map last year, I needed to first remove drawing feature on it (that draws a point and a line) to add specific ones (only lines). It should have been simpler to not rely on `OLMap` at all (less and clearer code).

Now, I want to add new layers based on components and the same problem arises, should I stick with the `OLMap` component or should I create a independent `YetiMap` one (with some code duplication on it)?

Both solutions can work, but I need your opinions/advice on this, and take the *right* solution beforehand.

Thanks!

**Comment by brunobesson** [comment]
AFAIU, building a new map component may be a better solution. I have already introduced async loading for yeti components, so this will have limited impact on user experience. When things differ too much, there is no meaning in keeping it in sync.
However, maybe you could still use some mixins and / or move common methods to utility files?

**Comment by cbeauchesne** [comment]
Hi @iamvdo,

I agree with @brunobesson. I originally thought that a single components would do the job, but there is too much features dedicated for one usage, and mixing all of them make things complicated.

I even hesitated to make a split for view pages and edit pages during my last PR : #1937 

So feel free to build the component that best fits your needs !

**Comment by iamvdo** [comment]
Thanks for your answers. I will follow that path.
