### ISSUE TITLE
Fix Google Analytics activation

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#2062]
Undo this line change: https://github.com/c2corg/c2c_ui/pull/1646/files#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R35

**Comment by brunobesson** [comment]
Nope. It is intended and working as expected. It is enabled by default, then enabled in `gdpr.js` if user allowed statistics cookies.

**Comment by cbeauchesne** [comment]
Indeed, it's not this line.

Though, Even if the cookie is enabled, nothing is sent to GA. There is an issue elsewhere.

**Comment by cbeauchesne** [comment]
Using `debug true`, on the console, even with acceptation of cookies: 

![image](https://user-images.githubusercontent.com/11915659/124726593-2ea47c80-df0e-11eb-9279-7dbdd3181015.png)

**Comment by brunobesson** [comment]
I don't get it, here's an extract of my account in production, where I enabled analytics, but not social media:
![image](https://user-images.githubusercontent.com/2234024/124745927-9f549480-df20-11eb-9a8d-b77ed26cc636.png)

I'll have a look anyway

**Comment by cbeauchesne** [comment]
Here is the stats: 

![image](https://user-images.githubusercontent.com/11915659/124746810-931d0700-df21-11eb-8dfe-1c24b54b2d98.png)

> Couldn't it be simply that most people disable it?

I would be surprised that almost 95% disable it (or maybe I would be pleased, it would mean that we could simply remove it :D  ) 

I'm surprised it works on your side, I may have missed something. Your screenshot is from your local dev server, or production server?

**Comment by brunobesson** [comment]
> I'm surprised it works on your side, I may have missed something. Your screenshot is from your local dev server, or production server?

On production. Could you check by yourself? Verify what you have allowed by clicking the `cookies` link in the menu sidebar bottom, then in dev console check out network calls.

> I would be surprised that almost 95% disable it (or maybe I would be pleased, it would mean that we could simply remove it :D )

Considering we apply the CNIL rule to have equivalent buttons to allow or disable all, I wouldn't be surprised at all.

**Comment by brunobesson** [comment]
Ok now I must confess there seem to be a problem. It is ok when you configure cookies. But then, if you reload the page, it doesn't seem to be taken into account properly, and nothing is sent.

I'll check.
