### ISSUE TITLE
Bug: Async loading components failed

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#2071]
Related to 8de7982d5, it seems that components are no longer loaded.

Tested at least on yeti page:

- choose an acceptable area
- set danger level and method
- compute risk

When image layer is added on map, a vertical slider control for opacity setting should appear on right. It used to work before the mentioned commit.

I'm not confident enough with that way of loading components. Can't tell if it's a bug or not.

Thanks!

**Comment by brunobesson** [comment]
I'm probably faulty, I'll have a look. I tested it, but probably not enough.

In the meantime, you can revert my commit for your developments and tests

**Comment by iamvdo** [comment]
Well, maybe a bit too quickly, it seems that there is a problem on our side. Will check that first.

**Comment by iamvdo** [comment]
Apologies, closing this. It works well. Bug is elsewhere, server side.
