### ISSUE TITLE
Bug: Allow to edit location by raw GPS coordinates

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#2085]
https://forum.camptocamp.org/t/saisir-les-coordonnees-gps/283599/3

**Comment by AntoineMarnat** [comment]
Shouldn't we just erase the "is hidden" that was introduced there ?

https://github.com/c2corg/c2c_ui/commit/13d082d178898eb4849ed23f9dc24650bd3dee4c#diff-0cf1aebd0037ea85966d8a5903e3432bed6e911de08103ff181fea1be7692651

**Comment by cbeauchesne** [comment]
Probably not as simple as this, the event flow between the map and the user is complex...
There are douzain of situation to check :(

**Comment by eddy-geek** [comment]
@cbeauchesne can you explain a bit what you did in this "Better outing's edition form" commit ?

**Comment by eddy-geek** [comment]
@AntoineMarnat  I tried quickly and the only drawback I see is that it impacts more than just the waypoints.

**Comment by brunobesson** [comment]
As far as I remember, @cbeauchesne encountered logical issues when keeping these fields. It would be nice to have its feedback; although I know he moved away from c2c development.

**Comment by AntoineMarnat** [comment]
> @AntoineMarnat I tried quickly and the only drawback I see is that it impacts more than just the waypoints.

The feature is usefull for routes (and to some extend for outings) as well.

**Comment by eddy-geek** [comment]
it's now available for everyone to test eg https://c2corg.github.io/c2c_ui/master/#/routes/add/fr

**Comment by eddy-geek** [comment]
somehow this was not closed by github, but it works well since #3779 was loaded :)
