### ISSUE TITLE
Find a solution to parse html entities

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#210]
https://c2corg.github.io/c2c_ui/bundle-analyzis.html

"he" dependencies is far to heavy : 30kb gzipped, close to 8% of the total weight of the build. It's too heavy for a feature rarely used. 

Possible solutions : 

* lazy loading 
* lighter lib
* js hack (I've saw some hint with textarea on stackoverflow) 

@brunobesson, any idea ? 😉

**Comment by brunobesson** [comment]
Lazy loading seems a good solution.
We do need a correct escaping of HTML entities. I do not know of any lightweight library for this, but maybe there is?

**Comment by cbeauchesne** [comment]
Well : 

* https://stackoverflow.com/questions/5796718/html-entity-decode
* https://stackoverflow.com/questions/1912501/unescape-html-entities-in-javascript

Two solutions : 

```js
const decodeHtmlEntities_textarea = function(input) {
  const textArea = document.createElement('textarea');
  textArea.innerHTML = input;
  return textArea.innerText;
}
```

And
 
```js
const decodeHtmlEntities_domparser = function(input) {
  const doc = new DOMParser().parseFromString(input, "text/html");
  return doc.documentElement.textContent;
}
```

test case to come...

**Comment by brunobesson** [comment]
I wasn't aware of this, thanks. There seem to be edge cases, but they do not concern us.
domparser solution is fine, then!

**Comment by cbeauchesne** [comment]
Done. If needed, my small code for testting : 

```js
  const decodeHtmlEntities_textarea = function(input) {
    const textArea = document.createElement('textarea');
    textArea.innerHTML = input;
    return textArea.innerText;
  };

  const decodeHtmlEntities_domparser = function(input) {
    const doc = new DOMParser().parseFromString(input, 'text/html');
    return doc.documentElement.textContent;
  };

  const testCases = [
    '&amp; &lt; &gt; &apos; &eacute; &egrave;',
    '<script>window.alert(666)' + '<' + '/script>',
    'a <div>html element</div>',
    'def => value',
    'value <= def'
  ];

  for (const test of testCases) {
    console.log('test     ', test);
    console.log('textarea ', decodeHtmlEntities_textarea(test));
    console.log('domparser', decodeHtmlEntities_domparser(test));
    console.log(" ");
  }
```
