### ISSUE TITLE
Displaying the list of routes linked to a document grouped by activity

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#2122]
To prevent many scrolling, Displaying the list of routes linked to a document grouped by activity with the possibility of opening or closing one activity

**Comment by cbeauchesne** [comment]
Discussion: https://forum.camptocamp.org/t/liste-itis-par-points-de-passage-case-recherche/284268

Add the same small arrown down button on the right side of each activity title above route list in waypoints' view pages : 

![image](https://user-images.githubusercontent.com/11915659/127823975-7a5410fd-aaa4-4e7a-b619-b786bd66710c.png)
