### ISSUE TITLE
Outdated CSS and performance improvements

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#2194]
Hello,

I was checking `src/assets/sass/checkradio-customisation.scss` and find some problems:

- Some selectors are bad copy/paste. It uses `::after`/`::before` twice, instead of `::after,:after`/`::before,:before` (as in https://github.com/c2corg/c2c_ui/blob/master/src/assets/sass/checkradio-customization.scss#L8-L9)
- But, do you still need IE8 support? (single colon pseudo-element are legacy CSS for IE8)
- Bulma also is adding both `::after, :after` (comment apart, not sure if that syntax is supported though, should be separate selectors: https://stackoverflow.com/a/10181948)

So if IE8 is no longer in scope, the double syntax should be removed imho. What do you think?

Second point, I want to make a PR to improve performance of animations (eg. use CSS transforms instead of `left`/`top`/`width`/`height`). Agree?

**Comment by cbeauchesne** [comment]
@brunobesson may have the most educated opinion on this

**Comment by brunobesson** [comment]
I'll fix the checkradio stuff.

As for your suggestion for animations, please do!
