### ISSUE TITLE
Bug: UI supports only 89% in France

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#2210]
## Issue

The soft goal set by the association was 95% of support in France. We are actually around 89%

```bash
> npx browserslist --config=.browserslistrc 
and_chr 92
and_uc 12.12
chrome 92
chrome 91
chrome 90
edge 92
edge 91
firefox 90
firefox 89
ios_saf 14.5-14.7
ios_saf 14.0-14.4
ios_saf 13.4-13.7
op_mini all
opera 77
safari 14.1
safari 14
safari 13.1
samsung 14.0

> npx browserslist --config=.browserslistrc --coverage=FR
These browsers account for 88.83% of all users in the FR
```

The main conf is this : `cover 95% in FR and > 0.4%`, the important part is `0.4%`.

## Action

Reduce `0.4%` as possible, regarding the delta on the bundle size.

https://forum.camptocamp.org/t/je-ne-peux-plus-me-connecter/287033/3

**Comment by brunobesson** [comment]
I used relaxed constraint to reach 95%.
