### ISSUE TITLE
Bug: Climbing indoor : remove routes

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2313]
Waypoints of the type "climbing indoor" should have no associated routes. Hence, we should do the following 2 things:

- For waypoints of the type "climbing indoor", remove the associated route section (in particular the create a route button)
- in the association tool, avoid to suggest "climbing indoor".

**Comment by brunobesson** [comment]
#2422 is a partial fix

The associated routes section is hidden.

As for the association tools, I added a dirty fix on the frontend side to disable associations in the association tool window. But this doesn't handle the case of association input (in the edit form). And this should be handled from the API side instead. I opened https://github.com/c2corg/v6_api/issues/1226

**Comment by AntoineMarnat** [comment]
Great, thanks for the fix!

Le lun. 27 déc. 2021 à 16:24, Bruno Besson ***@***.***> a
écrit :
