### ISSUE TITLE
Bug: Copyright licence for pictures

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2314]
The copyright licence should be available only to moderators, and used only for pictures of covers of books.

At the moment, anyone can change a licence to copyright.

**Comment by AntoineMarnat** [comment]
https://github.com/c2corg/c2c_ui/blob/f898ad09d976408e0eef825537e3fde780c08236/src/components/images-uploader/ImageUploader.vue#L142

At line:        [ <form-field class="is-narrow" :document="document" :field="fields.image_type" />](https://github.com/c2corg/c2c_ui/blob/f898ad09d976408e0eef825537e3fde780c08236/src/views/wiki/edition/ImageEditionView.vue#L9)

one should add a test is.moderator to enable/disable "copyright".

**Comment by lbesson** [comment]
Closed in the UI, but work still needed for the API
