### ISSUE TITLE
Feature: Add slovenian language for UI

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2334]

**Comment by AntoineMarnat** [comment]
Step 1 of the [procedure](https://www.camptocamp.org/articles/1205788/en/help-how-to-add-a-new-language-on-camptocamp) is done : [Slovenian is 100% translated ](https://www.transifex.com/camptocamp-association/c2corg_ui/language/sl_SI/)on Transifex.

Step 2 may happen quickly, as we have a good candidate to become a slovenian moderator.

**Comment by BorutK** [comment]
> Step 2 may happen quickly, as we have a good candidate to become a slovenian moderator.

That would be me (Borut). Thanks. 
Please note that @Dr_Chronos - a slovene speaker and a longtime c2c user - may also be a candidate.
