### ISSUE TITLE
Bug: Not all activities are loaded

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2338]
**Describe the bug**
Sometimes, on the edit page of documents, not all the activities are loaded/shown. It happens from time to time (FF 94), it can be solved by a simple refresh.

See also https://forum.camptocamp.org/t/suppression-dun-itineraire/145698/30

**To Reproduce**
? Maybe it is related to the hiding of the paragliding activity ?

**Comment by brunobesson** [comment]
Cannot reproduce. Are there steps for this?

**Comment by brunobesson** [comment]
Closing unless we have confirmation it still occurs.
