### ISSUE TITLE
Bug: map not centered after area link

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2353]
**Describe the bug**
When surfing on a area type document, if one clicks on the waypoints routes or outings link, the filtered map page is centered on France rather than the area.

ex: from https://www.camptocamp.org/areas/14173/fr/kenya  we ariive on a france centered map https://www.camptocamp.org/routes?a=14173

**Comment by flob38** [comment]
Maybe because this is specified : show-center-on-geolocation
https://github.com/c2corg/c2c_ui/blob/006e547366bec5dac6b8f51bb58f41e547bc1959/src/views/documents/DocumentsView.vue#L111-L117
(don't know how it works, especially with a PC)

**Comment by brunobesson** [comment]
I made a pull request to take area extent into account if possible. Please test. You can use multiples areas.

**Comment by AntoineMarnat** [comment]
Unfortunatly, the bug still holds (see same Kenya example).

**Comment by brunobesson** [comment]
The issue is closed, but the release not done yet. Let's do it now, you'll be able to test.
