### ISSUE TITLE
Feature: Climbing gear for bouldering

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#2459]
**Community discussion about this feature (mandatory)**
[Suggestion by Borut](https://forum.camptocamp.org/t/bug-materiel-sur-page-bloc/292284/3)

**Describe the solution you'd like**
Link to specific gear for bouldering instead of rock climbing

**Comment by brunobesson** [comment]
Waiting for the corresponding article to be created before making modifications to the code.
