### ISSUE TITLE
Bug: Licence missing on printed document

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#2484]
Licence is missing when printing a document

**Comment by brunobesson** [comment]
@flob38 why is it flagged with `need API modification`?

**Comment by flob38** [comment]
Because I wanted to insert version info : Anyway, wouldn't the most relevant value be the datetime of the last of both revisions? :)
But if you want to decorrelate the to things, feel free.

**Comment by brunobesson** [comment]
Version info is another issue: #1660. I'll remove the `need api modification` label then.

Are you willing / planning to work on this issue? If not, I can assign it to me.

**Comment by flob38** [comment]
Ok.
I've no time for this at the moment.
