### ISSUE TITLE
Bug: The map on "A proximité" search doesn't work on mobile

### ISSUE THREAD

**Issue by fbunoz** [c2corg/c2c_ui#2523]
**Describe the bug**
On mobile, on a topoguide doc page, when we click on the "A proximité" link, we reach the list of the objects near the preceding object.
But when we show the map, the map extend is the whole world, and the list is updated.
Then the purpose of the "A proximité" link is lost (it's like using the default list of this object type : need many manualy zooms to reach the wanted map extend).

**To Reproduce**

1. On a mobile browser, go to https://www.camptocamp.org/waypoints/45018/fr/dome-de-la-coche
2. Click on 'A proximité' in the bottom box : https://www.camptocamp.org/waypoints?wtyp=summit&bbox=658582,5645264,682766,5665264
3. Check that the first items are in the same area.
4. Click on the 'map' picto to switch to the map.
5. See the map extend : whole world.
6. Click on 'card' picto to switch to card list.
6. Check that the first items aren't in the same area.

**Expected behavior**
The map extend should be ~5 km around the preceding object.

**Desktop :**
- Device: mobile Samsung GS7
- OS: Android
- Browser Firefox
- Version 95.2.0

**Comment by asaunier** [comment]
The behaviour seems as expected on my laptop (recent FF) but indeed fails on my mobile FF.

**Comment by brunobesson** [comment]
At https://github.com/c2corg/c2c_ui/blob/a58e80eec22fd0bb9418252930b01d29e4640264/src/components/map/OlMap.vue#L428 the `map.getSize()` returns a 0 height when map is not shown, thus the problem.
