### ISSUE TITLE
Feature: Boulder grade with uppercase

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2552]
Boulder grades should have letters with uppercase, to emphasize the difference with sportclimbing.

See
https://fr.wikipedia.org/wiki/Cotation_en_escalade#Bloc

**Comment by florentcadot** [comment]
Issue can be closed if fine (seems good in production, example: https://www.camptocamp.org/routes/1525585/fr/l-elephant-sein-de-glace letter '7A' grade with letter capitalized).
