### ISSUE TITLE
Bug: [Minor] language on documents with maps

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#2625]
**Describe the bug**
When on a document with a map (waypoints, routes), if we click on itself on the map, the /lang is removed from the url. This adds the current language in the "see also in [set of lang]" part, which is expecially surprising when the document is in only one locale.

**To Reproduce**
Click on the icon on the map here : https://www.camptocamp.org/waypoints/45127

**Expected behavior**
the url should not change.

**Comment by brunobesson** [comment]
Inadvertently directly comitted to master...
