### ISSUE TITLE
Feature: add world wide satellite map layer

### ISSUE THREAD

**Issue by hemind** [c2corg/c2c_ui#2917]
https://forum.camptocamp.org/t/feature-request-add-world-wide-satellite-map-layer/305494

Recently I am adding some contents in China, but there is only OpenTopoMap available. And there is no option to add waypoint using coordinates (I remember before we have this). So every time I need first put the coordinates on [OpenTopoMap.org](http://opentopomap.org/) and check where the waypoint is and then come back to C2C and find the same location using the contour line. That’s painful.

So I am wondering if it is possible to add a world wide satellite map layer?

**Comment by AntoineMUPEC** [comment]
Do you have a specific world wide satellite map layer in mind ?

**Comment by hemind** [comment]
> Do you have a specific world wide satellite map layer in mind ?

I am thinking about the ESRI World Imagery. https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9

They said: 
> This work is licensed under the Esri Master License Agreement. https://www.esri.com/en-us/legal/terms/full-master-agreement

I have not fully understood their Terms of Use, but I somehow found this page which says developers can use the base layer up to 2,000,000 tiles/month for free. https://developers.arcgis.com/pricing/
