### ISSUE TITLE
Feature: On CPS portal, sort images by association date

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#3001]
As asked in [the discussion](https://forum.camptocamp.org/t/concours-photo-sophie-2022/305541/60), it might be more convenient to sort images in the CPS portal by association date to the article. Then, user can easily see the new images (and so does the jury ...) 

I do not believe it will biaise the contest (otherwise one should make a randomized order ^^).

Maybe, one should just change false to true in this line:

https://github.com/c2corg/c2c_ui/blob/0a15d150018e69f1ad6571f06bd13935c1649179/src/views/portals/SophiePictureContestView.vue#L81

?

**Comment by brunobesson** [comment]
I guess so. @cbeauchesne, you built this?
