### ISSUE TITLE
Feature: Improve naming of gpx/kml traces downloaded from camptocamp

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#3045]
**Community discussion about this feature (mandatory)**
[Link to <https://forum.camptocamp.org/> where this feature has been validated](https://forum.camptocamp.org/t/nom-des-traces-gpx/307603/11) https://forum.camptocamp.org/t/nom-des-traces-gpx/307603/12

**Is your feature request related to a problem? Please describe.**
When downloading the gpx (or kml) traces from outing s or routes, it's named after the document ID only, which makes it difficult to discriminates within multiples traces dowloaded. 

**Describe the solution you'd like**
For routes : automatically name the gpx (or kml) file with document ID + name of the summit + the name of the route
For outings : automatically name the gpx (or kml) file with document ID + name of the outing + date realized

**Describe alternatives you've considered**
maybe remove doc ID if name of the file is too long ?

**Additional context**
N/A

**Comment by lbesson** [comment]
https://github.com/c2corg/c2c_ui/blob/1bc9d7d53b4210245af84ec3d466d0642a57939f/src/views/document/utils/boxes/MapBox.vue#L145

**Comment by anakreenskyrider** [comment]
thanks !!!
