### ISSUE TITLE
Question: new linting rules?

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#3135]
Hello,
I noticed that the linting is not as strict as before (semicolon/commas can be omitted, new line at the end of line not mandatory, indentation not respected is ok, etc.)

Is it intended? Or just default behaviour that changed? Or a problem in my side?

Thanks!

**Comment by brunobesson** [comment]
Nothing should have changed in this side, we are still using and enforcing the use of prettier.

What are the symptoms? Does it pass CI?

**Comment by iamvdo** [comment]
It seems that prettier is for `ts,js,json,css,scss,less,md,html` files, not vue ones. Is it rather `vue-cli-service`'s lint?
I don't know if I can test CI in local...

Symptoms are what described: most common enforcing rules are not active...

**Comment by brunobesson** [comment]
Well, nice catch, `vue` files have been omitted when refactoring. I'll fix it ASAP.

**Comment by brunobesson** [comment]
@iamvdo I am not able to request your review for #3136 would you have a look anyway?
