### ISSUE TITLE
Feature: LoginView upgrade

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#3252]
The idea is to evolve the LoginView page, especially for account creation.

First: [BUG] the errors raised by the API for the username field are not sent to transifex and thus not translated. 

Second : there are a lot of fields related to at least 3 different names or pseudo, but registering should look as simple as possible to not deter potential users.

Idea : 
- Only ask for username, email and password.  (as simple as possible)
- Set name and forum_username by default with username. (to simplify)
- add a text explaination on the register page:

"username or email combined with the password will allow you to log in. Both username and email remain private. Username can not be changed, but email can.
By default, your pseudos on the topoguide and the forum is set to be your username, but you will be able to change it freely afterwards in the settings."

- add a text in the confirmation email:
"Your topoguide and forum pseudo were set to your username, once you log in you will be able to change it freely in the settings."

- unify with the wording of Discourse : "name", aka topoguide pseudo, should be "Nom d'utilisateur" ? (to do in Transifex)

**Comment by brunobesson** [comment]
There is a problem though with this approach: a valid forum username is far more restrictive than the others:
* between 3 and 25 characters
* no character except alphanumeric, dot and dash (i.e. no space)
* only [A-Za-z0-9] for first character (no accent)
* cannot end with 2 or more characters among [-_.]
* cannot end with something similar to most extensions (e.g. .js, .json, .gif...)
* must be unique (which implied uniqueness also with username and guidebook username)

Some of the conditions are quite peculiar and shouldn't occur too often, but still how do we handle this?
* we refuse if the username doesn't match a valid forum username
* we build a function to create a valid forum username from username, removing or mapping invalid characters, suffixing if needed, etc...
* we make the guidebook and forum usernames obvious with uneditable fields so the user understands the consequences
