### ISSUE TITLE
Feature: hyperlink for licenses in images

### ISSUE THREAD

**Issue by julienparis1** [c2corg/c2c_ui#3328]
**Community discussion about this feature (mandatory)**
[Post in forum ](https://forum.camptocamp.org/t/citations-de-c2c-dans-les-medias/105304/114)

**Is your feature request related to a problem? Please describe.**
Users, when they see a reference to the license under which a photograph is published on C2C, might have no clue as to what "CC by sa" or "CC by nc nd" means

**Describe the solution you'd like**
Mentions of licenses in images should appear as an hyperlink to https://creativecommons.org/licenses/ (more precisely the relevant page), as it already is the case in outings, routes, waypoints, articles, etc.

**Comment by flob38** [comment]
It's already a link at the bottom of the toolbox.
Should I understand you would like a link in the field "Image type" ?
![Capture d’écran_2023-03-03_21-42-26](https://user-images.githubusercontent.com/24532066/222825419-dd8e0954-26f9-46c2-930a-cd4c6146f301.png)

**Comment by julienparis1** [comment]
Exactly! I am not sure most users will go to the bottom of the page...

**Comment by julienparis1** [comment]
Merci!
