### ISSUE TITLE
page number should be reinitialized when changing object categories

### ISSUE THREAD

**Issue by LaurentBonnaud** [c2corg/c2c_ui#333]
Hi,

to reproduce this bug:

 - go to https://c2corg.github.io/c2c_ui/#/routes
 - clic on 2 to go to page number 2
 - clic on "Outings"

Expected result: the lastest outings from page 1 are displayed
Actual result: old outings from page 2 are displayed

**Comment by cbeauchesne** [comment]
Thanks @LaurentBonnaud  !

**Comment by LaurentBonnaud** [comment]
Thank *you* for the fix!
