### ISSUE TITLE
Bug: when searching on the map to recenter it automatically no action happens

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#3571]
**Describe the bug**
Bug: when searching on the map to recenter it automatically no action happens

**To Reproduce**

1. Go to map
2. search a place
3. validate or select it ith the mouse
4. it should recenter on the selected location
5. nothing happens :)

**Expected behavior**
4. it should recenter on the selected location

**Screenshots**
refer to : [https://forum.camptocamp.org/t/bug-centrage-de-la-carte/319573/4](https://forum.camptocamp.org/t/bug-centrage-de-la-carte/319573/4)

**Desktop (please complete the following information):**

- Device:PC
- OS: windows
- Browser chrome
- VersionVersion 115.0.5790.110 

**Additional context**
also reported for firefox

**Comment by florentcadot** [comment]
Here is a PR trying to fix this issue: https://github.com/c2corg/c2c_ui/pull/3787

**Comment by florentcadot** [comment]
Duplicated with https://github.com/c2corg/c2c_ui/issues/3568 I guess
