### ISSUE TITLE
Precise citation of sources

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#368]
Bibliography and external ressources are not precisely related to the information they provided, which is rarely the full information of a document.

The idea would be to implement a command to make it precise and easy to use.

For example, one could use a Tex-like command:

\cite( {book number on C2C or external url} ) 

providing a numbered note like on [wikipedia](https://en.wikipedia.org/wiki/Mont_Blanc#cite_note-6). A clic would open the book page or the url in a new page.

**Comment by cbeauchesne** [comment]
I close this issue, as it's a not a very common use case, and also because it's damn hard to develop
