### ISSUE TITLE
Add some explaination in edition forms' headers

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/c2c_ui#369]
Add a textual description in headers of edition forms (dedicated to each kind of document).
This text could describe what is expected in the document, remind the license of the content that will be typed, some guidelines or links to help article.

See https://forum.camptocamp.org/t/encart-dinformations-dans-les-formulaires-dedition/211168/3

**Comment by cbeauchesne** [comment]
@mgerbaux we need a precise text in english for each licence.

**Comment by cbeauchesne** [comment]
Added a message on forum : https://forum.camptocamp.org/t/encart-dinformations-dans-les-formulaires-dedition/211168/25?u=charlesb
