### ISSUE TITLE
In a doc page, move the summary box to the top of the content

### ISSUE THREAD

**Issue by fbunoz** [c2corg/c2c_ui#373]
The summary field is intended to show a text another place than description text field.
Today, the summary is showed just over the description : https://www.camptocamp.org/routes/927599/fr/tete-de-l-auriac-l-aiguille-la-voie-des-rats-morts
It should better to put the summary just under the title, with a police size a little bit bigger than normal size : 

![design_summary](https://user-images.githubusercontent.com/3902555/33836924-25e0e520-de8b-11e7-9ea4-0da2ecd1d259.png)

**Comment by cbeauchesne** [comment]
As we have deeply debated page ergonomy for this project, I consider this issue out-of-date.

If anyone think it's still an option, please go to the forum for a new proposal
