### ISSUE TITLE
Feature: Add autor in diaporama

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#3755]
**Is your feature request related to a problem? Please describe.**
The autor of the image should be mentioned with other informations.
![image](https://github.com/c2corg/c2c_ui/assets/24532066/30d37d43-60ac-4a30-bb39-f80f61868f63)

**Comment by florentcadot** [comment]
Here is a small draft PR for this feature: https://github.com/c2corg/c2c_ui/pull/3783

Draft PR because (as I've written in the PR description):
I've used the property `document.creator.name` as `document.author` datas seems null everytime, not sure about this

**Comment by florentcadot** [comment]
> > datas seems null everytime
> 
> Not everytime, for example : https://www.camptocamp.org/images/774866/fr/les-deux-bouts-de-cailloux-du-coin IMHO, you should test if the document.autor is null or not. If not, take the value, if null, take the document.creator.name.

Thanks for the example and quick reply :smile: , I've updated the PR with the logic you wrote in your message.
