### ISSUE TITLE
Feature: allow visible password

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#3797]
**Is your feature request related to a problem? Please describe.**
User should be able to see the password when they write it in order to correct wrong characters.

**Describe the solution you'd like**
Add a button to unmask password

**Comment by xiaomutoun** [comment]
Hello, I have made this pull request to add this feature https://github.com/c2corg/c2c_ui/pull/3811.
If someone can look at it. Thanks.

**Comment by florentcadot** [comment]
@flob38 one little question: do you usually close the issue when it's been deployed and tested ? If not this one should be closed as it's been merged (and it works fine, but I suppose the front has not been deployed since so the changes are not in production)

**Comment by brunobesson** [comment]
Fixed by #3811
