### ISSUE TITLE
Help to choose a route when creating an outing

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#380]
A few improvements that could be done to ease selecting a route when creating an outing:
* [ ] offer a way to get more details about selected routes. For instance open the route page in a new tab when clicking the cards?
* [ ] get more details when browsing the list of results in the association tool?
* [ ] it seems the relevancy of results could be improved. I have sometimes the feeling that keywords are not taken strictly as an "AND". Or perhaps the indexed data are not correct (eg. make sure description attributes are not indexed, only titles and associated docs?)

**Comment by cbeauchesne** [comment]
Duplicate of #400
