### ISSUE TITLE
Add link to google maps to travel from home to parking

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#389]
Another stuff from v5 now missing. IMHO, it's not very important, but it was requested on the forum, so some use it.

@lbesson is it on your TODO list?

**Comment by cbeauchesne** [comment]
I've red on forum that it's not really compatible with environment protection... :) 

I had then "need community approval" tag

**Comment by cbeauchesne** [comment]
Community discussion : https://forum.camptocamp.org/t/ajout-lien-vers-un-generateur-ditineraire-type-googlemap/251573
