### ISSUE TITLE
Items on map cannot be opened in new tab

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#392]
Currently:
* right-clicking doesn't offer to open waypoint/outing/... in new tab (it's not a link)
* midlle-clicking doesn't work
* ctrl-clicking opens the waypoint/outing in current tab

It would be nice to allow these commons behaviours on desktop.

**Comment by cbeauchesne** [comment]
Having a quick look : 

* I did not find a easy way to display icons inside html `<a>` tags (which is the good solution to have **the** good ergonomy)
* It could be possible to emulate a new tab with `window.open(url, "_blank")`, but we have to check all possibilities (middle click, right click, ctrl+click, cmd+click on mac...)

@brunobesson, do you have an opinion ?

**Comment by brunobesson** [comment]
No perfect solution at this point: looks like middle click isn't intercepted by default, so we would have to use some custom `Interaction`, or listen to `pointerup` event (but this would then cause problem if dragging ad such.
