### ISSUE TITLE
Show  associated images on image view

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#396]
In v5 it's possible to associate an image to another (for instance to associate a drawing with the original image). For instance: 
http://www.camptocamp.org/images/208579/fr/face-n-des-grandes-jorasses-quelques-itineraires
http://www.camptocamp.org/images/188564/fr/face-nord-des-grandes-jorasses

As for now I don't think it's possible in v6.

**Comment by cbeauchesne** [comment]
There is two issues in one : API does not shows association A > B if association B > A exists. : https://github.com/c2corg/v6_api/issues/530

And a gallery is missing if associations exists. Let's go with this : this issue will describe the UI part, and API issue will describe API part
