### ISSUE TITLE
Feature:  Suppressing emails from noreply@camptocamp.org when "Un usage excessif de l'API a été détecté"

### ISSUE THREAD

**Issue by agneshelmstetter** [c2corg/c2c_ui#3982]
**Is your feature request related to a problem? Please describe.**
All moderators receive many emails of noreply@camptocamp.org with subject "Un usage excessif de l'API a été détecté". This happens for instance when a contributor wants to print more than 100 outings. 

**Describe the solution you'd like**
Remove these warnings at least in the case of printing outings. Or increase the limit to 1000 documents per day.

**Comment by flob38** [comment]
API issue instead of UI ?

**Comment by flob38** [comment]
Open issue on API side
https://github.com/c2corg/v6_api/issues/1925
