### ISSUE TITLE
Search a route associated to an outing: add activity in the simple search filters

### ISSUE THREAD

**Issue by desnoes** [c2corg/c2c_ui#400]
Many times, the search for the route taken during the outing is not sucessfull because the results do not correspond to the selected activities. As an example, try to find the ski routes associated to 'chamechaude'. Only climbing routes are returned.
It is needed to consider the selected activity in the simple search procedure. To do so:

- [ ] modify \template\outing\edit.html (line 125) to add the selected activities
- [ ] modify simplesearch.js to add the activity as a filter for the search query (cf. app.SimpleSearchController.prototype.createAndInitBloodhound_ starting in line 330

Modifications are also required on the API side: cf. [issue 722](https://github.com/c2corg/v6_api/issues/722)

**Comment by cbeauchesne** [comment]
Actually, I think that result must also depends on map. So there is two solutions : 

1. add activity and bbox in search service
2. or use /routes?act&bbox

IMO, 2. is the best one, as it does not ask a modification on API.

@desnoes, @brunobesson, your opinion ?
