### ISSUE TITLE
Generic design issues

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#403]
This issue is a generic container for small and easy-to-fix design issues.

----

* [x] on mobile, margin are too big [Explication](https://forum.camptocamp.org/t/projet-ui-vos-retours-sur-le-design/237297/188?u=charlesb)
* [ ] on mobile, change box orders : tools, licence, association must come after content 
* [ ] hide scrollbar on ImageViewer : [explication](https://forum.camptocamp.org/t/projet-ui-fonctionnalites/234997/282?u=charlesb)
* [x] on history view, language label is in a disabled button. It should be a simple span
* [x] comment button is to wide on small screen and overflow.

**Comment by brunobesson** [comment]
> hide scrollbar on ImageViewer
This has been handled through #454

**Comment by flob38** [comment]
It seems that the 2nd point (hide scrollbar on ImageViewer) is already solved : the scrollbar isn't above the image anymore. Do we hide scrollbar anyway ?

**Comment by cbeauchesne** [comment]
@flob38 , yes, if there is an easy way to remove it (I mean, not a hack). But it's obvioulsy a detail :)

**Comment by flob38** [comment]
There's something strange with the toolbox : associated documents are in the toolbox, so when we put the toolbox after anything else on mobile, the associated documents are after the comments...
![image](https://user-images.githubusercontent.com/24532066/56845940-fc784880-68c8-11e9-810d-a27e6b45b7e7.png)
That's what is required in the list above, but to me, it's make more sense to put associated documents just after associated outings and routes and before comments. What do you think ?

**Comment by cbeauchesne** [comment]
> What do you think ?

It will be a little difficult to totally split data : we are in front of limits of an UI that tries to be as good as possible on mobile AND desktop... 

Another (easy) possibility : add a small arrow that expand/collapse comment box : at least, toolbox (and thus, associated doc) won't be so far.

On an other hand, I think that we should list here what is techniclly possible (eg without falling in a high complexity), and let community choose.
