### ISSUE TITLE
Bug: wrong display of BRA zones in routes

### ISSUE THREAD

**Issue by jbeilin** [c2corg/c2c_ui#4128]
On the ski routes, a new feature displays the BRA danger lever and just under several link to the BRA pages. 

In almost all areas, 3 links are displayed : the right one, and 2 more Haute-Tarentaise and Karkonosze. If the route is in Haute-Tarentaise BRA zone, only 2 links are displayed  : Haute-Tarentaise and Karkonosze. 

![Capture d’écran du 2024-11-19 23-53-01](https://github.com/user-attachments/assets/ec549307-7da1-4570-9c9a-73b32b00ac8b)

**Comment by brunobesson** [comment]
Looks like turf intersect doesn't like polygons with strange coordinates (don't know how to describe it):

(Haute Tarentaise)
![image](https://github.com/user-attachments/assets/89dacec5-16a3-412c-92af-4a7368a7e1fc)

(Karkonosze)
![image](https://github.com/user-attachments/assets/1110ce38-ed95-4541-8c00-d119b1569592)

**Comment by jbeilin** [comment]
Ok, I will try to correct these geometry but as some BRA zones are dynamically created (Switzerland, Italy), it may happen again in the future.

**Comment by brunobesson** [comment]
Indeed, and I am working on a fix on the UI side. Looks like turf-buffering the geometry with 1m offset is enough to clean the polygon:

(Haute Tarentaise)
![image](https://github.com/user-attachments/assets/b14447d7-eeea-41cd-9185-a0428eaeeba1)
