### ISSUE TITLE
Ellipsis on left column links

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#413]
> Colonne gauche : si les titres sont longs, la fin en est cachée. Est-il possible de revenir à la ligne ? https://c2corg.github.io/c2c_ui/#/routes/1073751/fr/torrent-de-boussac 

=> Fix must be discussed on forum, both solution has their pro/con

**Comment by brunobesson** [comment]
What is the con on this case? There is no size problem caused by cards requiring same height or anything similar, oes it?

**Comment by cbeauchesne** [comment]
Only one con : can take huge vertical place : 

![image](https://user-images.githubusercontent.com/11915659/55399461-724bf700-554b-11e9-8217-15ee5de50bcf.png)

By the way, I think a small rework on V6 solution may be a good compromise : 

![image](https://user-images.githubusercontent.com/11915659/55399707-28174580-554c-11e9-8c8b-64d8898a2067.png)

**Comment by cbeauchesne** [comment]
And other question : does elevation is really relevant here ?

**Comment by brunobesson** [comment]
> can take huge vertical place

Using ellipsis instead of having multiple lnes won't really hcnage things (most titles will stay on one line, some on 2, and none more).

>  I think a small rework on V6 solution may be a good compromise
I approve this change

> does elevation is really relevant here ?

Yes, I do thinl so.

**Comment by cbeauchesne** [comment]
Ok, let's ship with that so.
