### ISSUE TITLE
Popup filter is too low

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#418]
When a lot of association filter are present, other popup came too low on screen : 

![image](https://user-images.githubusercontent.com/11915659/55465808-302fbd80-55fe-11e9-938b-79d3b934a3d1.png)

**Comment by cbeauchesne** [comment]
On a more global vue, this component must no go to the next line.

**Comment by cbeauchesne** [comment]
The UI on this point need to be improved a lot.

**Comment by ataraxido** [comment]
I had the idea to reduce the size of the tags when there are many ( > 2), it's not of course solving this issue but improving a bit the display.

From
![Screenshot_2020-11-24 Sorties - Camptocamp org(1)](https://user-images.githubusercontent.com/6763663/100112072-1eec9200-2e6f-11eb-9a6e-267f07300373.png)
To
![Screenshot_2020-11-24 Sorties - Camptocamp org](https://user-images.githubusercontent.com/6763663/100112090-214eec00-2e6f-11eb-8ba7-27f93ee4a245.png)

**Comment by cbeauchesne** [comment]
As long as it takes more than one row, it's a bug. We need to find a solution where it never go to next line, OR fix the dirty job I did on the vertical space used by the list. 

On other hand, this usage is definitly not a very common one, so it's not very urgent.

**Comment by brunobesson** [comment]
Fixed by #1721
