### ISSUE TITLE
Swiper: hide buttons in some cases

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#453]
* On mobile: on tap, buttons and arrows should be hidden/revealed
* On desktop: buttons should disappear when mouse does not move for a certain amount of time, re-appear on move

This is the behaviour we had and v6, and I found it particularly nice. Not that hard to reproduce now.

I should check the bahviour for legend, I don't remember

**Comment by flob38** [comment]
If I remerber well, behaviour for legend depended on the browser (fixed on Firefox and hidden/revealed on Chrome, or vice versa).

**Comment by brunobesson** [comment]
I don't remember of any difference depending on the browser. Photoswipe's documentation details the behaviour I described above.

**Comment by flob38** [comment]
I was just talking for legend, not for the buttons and arrows. There wasn't something specific for different browsers, it was from css interpretation. But maybe this was at the really start of the v6 and it's was solved later.
