### ISSUE TITLE
Allow "not known" value for glacier_gear field on routes

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#457]
It may need an API modification ? 

Techniccly, it means that null should be interpreted as "not known"

**Comment by AntoineMarnat** [comment]
Should we just display "unknown" whenever activity is Snow&Ice and field is null ?

**Comment by brunobesson** [comment]
> Should we just display "unknown" whenever activity is Snow&Ice and field is null ?

I would say so, if we focus on improving the guidebook.

**Comment by AntoineMarnat** [comment]
At the moment, the code reads:
`<field-view v-if="document.glacier_gear != 'no'" :document="document" :field="fields.glacier_gear" />`

Meaning it is displayed only when "yes", aiming to not spam with useless "no" information.

To this extend, I would suggest to do the same with lift access: display only with yes. What do you think ?


I suggest to be slightly more subtle for theglacier_gear field

Display if the value "no" and activity is 
`const glacier_activities = ['mountain_climbing', 'skitouring', 'snow_ice_mixed', 'snowshoeing'];`

Display "unknown" if value is null and activity is ('mountain_climbing' or) 'snow_ice_mixed'.

What do you think ?

**Comment by brunobesson** [comment]
I would agree with your proposal.

> Meaning it is displayed only when "yes", aiming to not spam with useless "no" information.
Not if there is also the undefined value.

**Comment by AntoineMarnat** [comment]
I tried something, but I need to understand more the <field-view>.

**Comment by cbeauchesne** [comment]
call me if you need some help on this point

**Comment by brunobesson** [comment]
I am not sure what to do with this old issue. There is no route in the guidebook where the value is not set. When creating a new route, the default value is no.

Do we need to modify the behavior so that the value is not set bey default (`not specified` presented on th UI side), maybe only for some activities?

I would favor closing this issue.

**Comment by AntoineMarnat** [comment]
I think we can close this issue and remove my branch.

Le mer. 8 mars 2023 à 10:31, Bruno Besson ***@***.***> a
écrit :
