### ISSUE TITLE
More userfriendly title for outings in the associations's form

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#480]
Trying to associate an outing (to an xreport for exemple) isn't easy because the title displayed in the search list is often not very obvious.
Adding the date and the user who created the outing would be nice.
![image](https://user-images.githubusercontent.com/24532066/55652787-df31ec00-57ec-11e9-8e2e-abb88ebeb6b4.png)

**Comment by cbeauchesne** [comment]
Agree. And as title are in most case the same, the format should be : 

date - user - title

With .ìs-ellipsed` class on title

**Comment by flob38** [comment]
Should I create a new PrettyOutingAssociatedLink ?
With the PrettyOutingLink, I must be able to hide the quality, condition, images and gps, but I don't think it's possible to put the username before the title.

**Comment by flob38** [comment]
Why sould we have `.is-ellipsed` class on title ? The route are not ellipsed.

![image](https://user-images.githubusercontent.com/24532066/55674571-ab22fd80-58b6-11e9-84f3-1997f362bbb4.png)

**Comment by cbeauchesne** [comment]
> Should I create a new PrettyOutingAssociatedLink ?

Yes, it will be cleaner. Can you also move AssociationItems, AssociationsWindow, and your new component into /src/components/association-editor folder?

> Why sould we have .is-ellipsed class on title ? The routes are not ellipsed.

A feeling of my part, as outings names are often the same. But I may be wrong, feel free to do it as you feel it :)
