### ISSUE TITLE
Modérator : merging pop up

### ISSUE THREAD

**Issue by anakreenskyrider** [c2corg/c2c_ui#483]
When merging 2 documents the popup is not high enough : when target document is searched and appears under the search box, it can not be directly selected a scroll down with the ascenseur is needed;
it would be better to have it directly accessible to clic on the target file/
![Sans titre](https://user-images.githubusercontent.com/49275256/55667602-8bf88180-585e-11e9-8cc2-bf3fea4788a4.png)

**Comment by anakreenskyrider** [comment]
NB je vois aussi que c'est pas traduit !

**Comment by cbeauchesne** [comment]
En effet :)
