### ISSUE TITLE
On Microsoft Edge - Can't save images when download

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#486]
With Microsoft Edge, when trying to add some images to a document, after you have chosen your files and put then in the image dowload box, you can't save them because the "Save" button is always desactivated (and the "trash" button doesn't appeared either).

A single error occurs when adding files : 
```
SCRIPT438: Object doesn't support property or method 'toBlob'
ImageUploader.vue (169,1)
```

**Comment by cbeauchesne** [comment]
@flob38 could you test with github pages please? (I do not have any way to test it with edge)...

Thanks a lot !

**Comment by cbeauchesne** [comment]
When it's released, please leave a message on https://forum.camptocamp.org/t/ajouter-des-images/241357/10?u=charlesb

**Comment by cbeauchesne** [comment]
Ok, tested and approved by @flob38 , thanks a lot!
