### ISSUE TITLE
Profile - non associated images in the viewer

### ISSUE THREAD

**Issue by BorutK** [c2corg/c2c_ui#489]
On the Topoguide Profile page, the viewer contains more images than the ones associated.

Examples : https://forum.camptocamp.org/t/profil-topoguide-images-associees/241315

**Comment by cbeauchesne** [comment]
Notice : 

Image viewer (component that display full size image) show **all** images presents on a page. In consequence, you'll see on it images associated to user's profile, but also images displayed on user feed.

In consequence : 

> it's not a bug, it's a feature

😄

**Comment by BorutK** [comment]
😄
