### ISSUE TITLE
Add summary for books on feed cards

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#504]
Actually, this field is not provided by API

**Comment by brunobesson** [comment]
@cbeauchesne API change, could it be as simple as to add `locales.summary` in `LISTING_FIELDS` from https://github.com/c2corg/v6_common/blob/master/c2corg_common/fields_book.py? (then  update rquirement on v6_common, etc).

**Comment by cbeauchesne** [comment]
I don't know. In a perfect world, it should. But the API has some logic and data deduplication sometimes :(

**Comment by brunobesson** [comment]
Change is OK on the API side: https://github.com/c2corg/v6_api/issues/1028
Once the API v6.8.0 is live, this issue will be fixed. There is nothing to do on the frontend side.

**Comment by brunobesson** [comment]
v6.8.0 is live.
