### ISSUE TITLE
On association editor, links must open pages in new tabs

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#513]
https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/131?u=charlesb

**Comment by brunobesson** [comment]
Don't use know how to ctrl+click? 🙁

**Comment by cbeauchesne** [comment]
@b_b, in a perfect world, yes, everyone should know what is Ctrl + click, and never miss it.

But IMO, when it's obvious that a link will always be open in a new tab, and when opening it in the same tab will causes a poor user experience (the loss of an action not yet saved), I think it's preferable to force it.
