### ISSUE TITLE
Misc bugs on IE11

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#530]
See https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/146?u=charlesb

**Comment by brunobesson** [comment]
Simple answer: do *not* support a browser dropped by its creator and used on less than 2% of the time. Those still using it deserve to live in crusted snow forever 🙂

**Comment by cbeauchesne** [comment]
I would love to do that. Unfortunatly, stats from past 7 days show this terrible fact : 

![image](https://user-images.githubusercontent.com/11915659/56243985-21381900-609c-11e9-96ff-036df7ff1405.png)

Such a pity that ie took more market share than Edge (around 2%). Even the recent move from MS to switch Edge core to Chromium won't solve this 😢 

My position is that we must stick to the 95% audience target, and thus keep IE11 in our official supported browsers. But once blocking bugs are fixed, I prioritize issues regarding audience. And as a direct consequence, an issue in a browser with 4% of audience is rarely a priority.
