### ISSUE TITLE
Do not display geolocated image on map on routes pages

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#541]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/165?u=charlesb

**Is your feature request related to a problem? Please describe.**
On route page, geolocated associated images are shown on map. It's not relevant

**Describe the solution you'd like**
Do not show geolocated images on map

**Comment by BorutK** [comment]
Hello !
Had this point really been decided upon on the c2c forum ? I remember the point having been brought up, but I can't remember a decision having been made - maybe I just didn't pay attention.

**Comment by cbeauchesne** [comment]
Better place for the comment :) 

So, you have the link on top of issue. Actually, nobody answered to Antoine's request, and it seems to me coherent to have images only for outings. Feel free to answer to Antoine on forum if you think we must change this behavior (it's very simple to adapt).

**Comment by cbeauchesne** [comment]
Note : As it's released, I close the issue. If we decide to modify this behavior, I'll create another one.
