### ISSUE TITLE
When creating a new waypoint, there is no card to georeference it

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#559]
**Describe the bug**
When creating a new waypoint, there is no possibility to position on the map. Instead, one must use the geolocation input fields.

If one doesn't, then document cannot be saved, a popup "lang: required" appears and a red text originating from invalid geometry code is printed below the document title.

On the contrary, editing an existing waypoint displays the map.

**Screenshots**
![image](https://user-images.githubusercontent.com/2234024/56155440-2d987500-5fbb-11e9-841c-02db27254877.png)

**Comment by cbeauchesne** [comment]
Strange, it seems to be another root cause that block the display of elements. Do you have an error in console? does you see the same symptoms on your dev env?

On chrome, it actually works on production for me

**Comment by brunobesson** [comment]
Reloading the page solved this.
There must be a problem somewhere, why aren't the js files not updated properly?

**Comment by cbeauchesne** [comment]
weird, no idea...
