### ISSUE TITLE
Association form - No name/link for image without title

### ISSUE THREAD

**Issue by flob38** [c2corg/c2c_ui#561]
**Describe the bug**
In the association form, if an image doesn't have a title, the link to the image doesn't exist and the line doesn't have text to "describe" the image.

**To Reproduce**
For exemple, go to https://www.camptocamp.org/outings/1069334/fr/pointe-centrale-n-du-ferrouillet-couloir-sw
Open the association form

**Expected behavior**
If title exists, it's shown before the buton and when you click it, it's openning the image document.

**Screenshots**
![image](https://user-images.githubusercontent.com/24532066/56160130-a5b86800-5fc6-11e9-9367-928335edccc9.png)

**Desktop (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Comment by flob38** [comment]
See forum : https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/194

Add title, author and date except on mobile (lack of place) : only title is available. Author is available but means the person who shot the photo and not the one who create the image on c2c.

**Comment by cbeauchesne** [comment]
I propose to not include contributor name in this : https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/198?u=charlesb

IMO, image itself is enough, and this feature does not justify an API change. We'll see what community says.

**Comment by cbeauchesne** [comment]
No reaction on forum, we'll do with available data from API
