### ISSUE TITLE
Slight changes to forum look and feel

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#584]
* no bold font anymore
* no ellipsis

**Comment by cbeauchesne** [comment]
It's an issue about forum (discourse), or UI ?

**Comment by cbeauchesne** [comment]
Ok, seen #574.

Are you really sure for `is-ellipsed` ? Some thread titles may be very long. On dashboard, were design is more dense, to keep a good averview on one page screen, it looks weird (i've exageratly reduced the screen width to simulate a use case where we have a lot of long-title threads) : 

![image](https://user-images.githubusercontent.com/11915659/56455283-bd904300-635c-11e9-9f59-b87cc1a60ce6.png)

**Comment by brunobesson** [comment]
UI feed. It's merged already :-) (or at least so I remember)
