### ISSUE TITLE
Forums' icons on feed can be reduced

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#610]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11915659/56867984-b1575600-69ec-11e9-8d13-6a6608bbec05.png)

**To Reproduce**
Maybe when there is two lines ? 

https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/233?u=charlesb

**Comment by cbeauchesne** [comment]
Browser  : firefox

**Comment by brunobesson** [comment]
Looks like adding `flex-shrink: 0` on the `img` tag does the trick.

**Comment by cbeauchesne** [comment]
@brunobesson can we merge this PR? I plan to do a release today or tomorrow.

**Comment by brunobesson** [comment]
Please do.
