### ISSUE TITLE
On safari, fullscreen markdown editor does not expand to full height

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#616]
**Describe the bug**
On safari, fullscreen markdown editor does not expand to full height

https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/215?u=charlesb

![image](https://user-images.githubusercontent.com/11915659/57281108-951d7e00-70aa-11e9-9626-e2ae018eb605.png)

**Comment by jeanphilippeds** [comment]
Hello,

I tried to reproduce this issue and I think it's working.

### Conditions:

- Safari 15.5
- macOS Monterey 12.4
- Macbook Pro M1 14" 2021

### Screenshot:
<img width="1512" alt="Capture d’écran 2022-09-26 à 21 14 44" src="https://user-images.githubusercontent.com/22117220/192360909-dbd4a052-a9bf-447f-8989-8bf8b158f50b.png">

**Comment by brunobesson** [comment]
I have no mac, so I cannot test it on my side. Thanks for doing so on your side.
Good to know it has been fixed with recent Safari.
Because this issue isn't really lively, I suggest we close it, we can reopen if someone mentions it.
