### ISSUE TITLE
Filters ergonomy on mobile

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#617]
**Describe the bug**
On mobile screens, if there are too many filters, users can't acces to the bottom of dropdown : 

![image](https://user-images.githubusercontent.com/11915659/57282409-46251800-70ad-11e9-9dd4-0fc584e3282d.png)

**Comment by cbeauchesne** [comment]
this bug is awfull... do not stale

**Comment by jeanphilippeds** [comment]
I fixed this issue [in this commit](https://github.com/c2corg/c2c_ui/pull/3005/commits/3c0a0e6e8d22e2b7ca4dac3cfa94277cf276f334)
