### ISSUE TITLE
Duplicated alert when leaving edition forms

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#625]
**Describe the bug**
When you leave an unsaved edition form, an alert is displayed : "You have unsaved changes....". Sometimes, it's displayed a second time.

**To Reproduce**
1. log in
2. https://www.camptocamp.org/routes/add/fr
3. Click on big green plus button > add a route

**Expected behavior**
Only one alert

**Comment by brunobesson** [comment]
I do think this issue has been fixed by the router update. Because the URL is the same, the page is not reloaded.
Are there other cases where this behaviour can be reproduced?

**Comment by cbeauchesne** [comment]
I confirm that I can't reproduce. 

Nope, I don't know any other case that reproduce it. I guess we can close it. Thank's for checking! :)
