### ISSUE TITLE
Outing's date doesnt mention year for outings older than one year

### ISSUE THREAD

**Issue by brunobesson** [c2corg/c2c_ui#630]
See e.g. https://www.camptocamp.org/outings/258490/fr/le-chatel-ou-bonnet-de-calvin-versant-s-par-la-grande-vire-de-pomaray, an outing from 2011.

**Comment by cbeauchesne** [comment]
Mmmmh, I don't see the point : 

![image](https://user-images.githubusercontent.com/11915659/57625396-1174fd00-7594-11e9-8129-7f6aa1e66f71.png)

**Comment by brunobesson** [comment]
Holly f**, I was doomed by the line return:

![image](https://user-images.githubusercontent.com/2234024/57629175-a29ba200-759b-11e9-9a3f-312fc76cd59a.png)


Maybe we should ensure it stays on one line?

Anyway, closing this issue.

**Comment by cbeauchesne** [comment]
> Maybe we should ensure it stays on one line?

Makes sense :)
