### ISSUE TITLE
Sort associated route on waypoints, books...

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#754]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/projet-ui-liste-des-itineraires-associes-a-un-point-de-passage/235962/76?u=charlesb

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On https://www.camptocamp.org/waypoints/37582/fr/mont-blanc-du-tacul, on associated routes block, sort items by title, instead of by id

**Describe alternatives you've considered**
Rating ? may be hard to choose one

**Additional context**
N/A

**Comment by asaunier** [comment]
Isn't it rather an API issue?

**Comment by cbeauchesne** [comment]
Depends on how we want to implement this. But I think it's more a UI job : API provides data, and UI shows it.  

That said, I think that if something must be done on API side, it's increasing the limit of associated items provided by API.

**Comment by asaunier** [comment]
As the API provides only a subset of associated docs (when there are more then 30?), if you do the sorting on the UI side, you will probably miss some results.
And again it's probably something that would be useful for other UI clients?

**Comment by cbeauchesne** [comment]
I do not get your point : if some results are missing, they are missing whatever it's sorted by id or by whatever else.

**Comment by cbeauchesne** [comment]
Saying it differently, I think that the long term solution is to include **all** associated routes on waypoints, not a subset. And then, the UI do its own stuff to display it.

If the long term solution is to keep a subset of associated routes, the you're right : we should sort the result on API side in order to have a consistent result. Note on this : if it's sorted on rating, this consistency is a feature. But if it's sorted on title, this consistency is for the sake of glory...

**Comment by brunobesson** [comment]
IMHO, this list should not be restrained, except maybe on books, areas and such (in which case the limit could be higher, like 100?). It's confusing to only have an extract of the associated routes for a waypoint.

**Comment by brunobesson** [comment]
> is to include all associated routes on waypoints

Exactly, and not only for waypoints (with some exceptions mentioned above). Even in that case, I do think the API has proven robust and fast enough to handle it.

**Comment by asaunier** [comment]
> I do not get your point : if some results are missing, they are missing whatever it's sorted by id or by whatever else.

True.

> the long term solution is to include all associated routes on waypoints, not a subset.

I don't remember exactly why only a subset is returned. Perhaps because in some cases ("super"-waypoint) you could have a ton of associated routes. For instance https://www.camptocamp.org/waypoints/42284/fr/aiguilles-de-chamonix-et-envers-des-aiguilles- has >200 associated routes.

**Comment by cbeauchesne** [comment]
I think it's for performance issue, and after reflexion, I think we should keep it : otherwise, DDOS attack could be made with simply associate several super-waypoints.

That said, if we put a bigger limit (let's say few hundreds), it would be a good compromise by covering 99% of the use cases, and will push moderators to think of a better organization : I'm note sure that "aiguilles de chamnoix" can be considered as a localized waypoint :)

**Comment by brunobesson** [comment]
OK, once API v6.8.0 is live, the limit will be extended to 400 associated routes. We can thus sort the documents without too much question.
I assign this issue to myself and will make a proposal.
