### ISSUE TITLE
Better display of image timestamp

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#755]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/affichage-heure-des-photos/244096

**Is your feature request related to a problem? Please describe.**
Timestamp display is technical on images

**Describe the solution you'd like**
Display a pretty format for image timestamp

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by asaunier** [comment]
I agree displaying the timestamp with a UTM format makes it hard to read.
I would suggest to display it as is, as it's done by the way in the editing form.

For instance with this image: https://www.camptocamp.org/images/1141564/fr/
The viewer shows:
![Screenshot from 2019-08-21 10-08-50](https://user-images.githubusercontent.com/1192331/63414397-100d6900-c3fc-11e9-80c3-4350b20ba459.png)

whereas the editing form shows:
![Screenshot from 2019-08-21 10-08-03](https://user-images.githubusercontent.com/1192331/63414415-1ac7fe00-c3fc-11e9-99c0-a36e4f18805a.png)

Could we display the timestamp in the viewer as in the editing form?

**Comment by cbeauchesne** [comment]
yes, that's the plan :)
