### ISSUE TITLE
date_start and date_end filter is missing on /outings

### ISSUE THREAD

**Issue by cbeauchesne** [c2corg/c2c_ui#758]
**Describe the bug**
date_start and date_end filter is missing on /outings

It's mainly an UI issue : how to display nicely the calendars.

Then, simply add url properties on date_start and date_end definitions in fieldProperties.json

**Comment by joffreyverd** [comment]
Hi @cbeauchesne,
So if I understand correctly I should just add to the `date_start` & `date_end` properties an `url` property in `fieldsProperties.json` ? With what value ?
I suppose there is no need to update `documentsProperties.json` which is automatically generated by the translation tool?
Thanks for the info!

**Comment by cbeauchesne** [comment]
If only :) 

`documentsProperties` and `fieldProperties` describe the object model from API, and no, unfortunatly, none of them is generated.

> So if I understand correctly I should just add to the date_start & date_end properties an url property in fieldsProperties.json ? With what value ?

Nope, it's a little bit more complicated. Few example are far better than a long explanation : 

* https://www.camptocamp.org/outings?date=2019-08-22 => `WHERE date_start <= 2019-08-22 AND date_end >= 2019-08-22`. In good english, the given date must be included in date range defined by the outing
* https://www.camptocamp.org/outings?date=2019-08-22,2019-08-25 => `WHERE NOT (date_start > 2019-08-25 OR date_end < 2019-08-22)`. In good english, at least one of the day in date range defined in input must be included in date date range defined by the outing.

So there is no mapping between object field `date_start` and `date_end`, we must build from scratch a MVC widget that handle the `date` url field.

**Comment by ataraxido** [comment]
Since the date filter is mainly used in order to have something consistent with what you plan in terms of weather conditions, what do you think of only displaying the start date filter ?

**Comment by cbeauchesne** [comment]
You means, use only the first pattern in my example ?

**Comment by ataraxido** [comment]
I was thinking more in terms of UX but yes, it leads to use only the first pattern of your example

**Comment by cbeauchesne** [comment]
It'd a good start! And as it's way more esy to implement, I'd be very happy with it :)

**Comment by ataraxido** [comment]
Damn, that's nice :dancing_men:

**Comment by cbeauchesne** [comment]
Thank's a lot @ataraxido 

Here is the demo of your change: https://c2corg.github.io/c2c_ui/master/#/outings 🚀

**Comment by cbeauchesne** [comment]
Side note @ataraxido, do you have a camptocamp account ? We have a dev group on the forum where we  discuss about dev topics (open to dev, and to c2c association members). If you're willing to, it's a good idea to be in those discussions.

**Comment by ataraxido** [comment]
I do yes, of course @cbeauchesne : https://www.camptocamp.org/profiles/1072399/en/jeremy-l & https://forum.camptocamp.org/u/jeremyl
