### ISSUE TITLE
Route page : add link to contextual help about ratings

### ISSUE THREAD

**Issue by fbunoz** [c2corg/c2c_ui#763]
https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/381

On route page, the ratings need  contextual help. 
As all the ratings age showed on one line, a solution is to add a link on each rating.
Underline a rating on mouse over.
On mobile, no underline, just links. 
An (i) picto can ne added at the en of ratings line, to open a tooltip which explain to click on a rating to open ifs help.

**Comment by cbeauchesne** [comment]
After discussions on forum : https://forum.camptocamp.org/t/nouvelle-interface-bugs-questions-suggestions/241148/483?u=charlesb

Small spec : 

* Add a blue rounded **i** on cotation line on route and outing pages (only at the top of the page, not on cards, or on pretty links)
* on click on this **i**, open a popup. In this popup, list all documents ratings values (one per line), and add a link to the help page.

**Comment by cbeauchesne** [comment]
After this https://forum.camptocamp.org/t/aide-contextuelle-pour-les-cotations-proposition/251220/24

Use a dropdown i/o a popup
