### ISSUE TITLE
Xreport: show associated documents

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#774]
**Describe the bug**
On the page of a Xreport, the associated  routes are not shown. Other documents (outings,waypoints, picture, article) are shown.

**To Reproduce**
Check:
https://www.camptocamp.org/xreports/1146425/fr/accident-ossau-traversee-4-pointes5
and clic on "modify associations".

**Expected behavior**
Associated routes should appear to the left, like any other pages.

**Comment by anakreenskyrider** [comment]
Outings appears, but not associated routes
