### ISSUE TITLE
Feature: Reduce the visibility of the listing of paper maps

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#844]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/presence-des-liens-vers-les-cartes/252265/8
It has been discussed, that the information related to the paper maps should not disapear but its visibility should be reduced.

**Describe the solution you'd like**
It should stay close to the map display, mayby a drop-down menu "Paper map" next to the icones KML GPX ?

**Comment by cbeauchesne** [comment]
AS now, the discussion is not finished :)
