### ISSUE TITLE
Feature: elevation gain in the line description of a route

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#845]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/details-de-laffichage-des-itineraires-lies-a-un-point-de-passage/252602/4

**Is your feature request related to a problem? Please describe.**
The elevation gain displayed is the elevation gain of the difficulties. It is very good for the mountaineering activities, but for skiing, snowshoing and walking it would make more sens to display the total elevation gain.

**Comment by cbeauchesne** [comment]
@AntoineMarnat : 

>  but for skiing, snowshoing and walking it would make more sens to display the total elevation gain.

Do we need to display both, or only total elevation for this routes?

What about bi-activities routes ?
