### ISSUE TITLE
Bug: Zoom events on OLMap are fired only when zoom is integer

### ISSUE THREAD

**Issue by iamvdo** [c2corg/c2c_ui#887]
On YETI, when a user zooms using touch (on mobile) and/or trackpad (when pinch, scroll), zoom events are not fired, as they are no longer integer. So, computation could no longer be done (as zoom will never be updated).

I will fix it, but I need your point of view on a solution:

- Fire all zoom events from `OLMap.vue`
- or, (for me a better solution) remove `change:resolution` event and no longer fire zoom events from `OLMap` (seems that only YETI uses them, added in 605e6da8698f), and let YETI do its own work (already a `moveend` event that can be used)

**Comment by brunobesson** [comment]
This is a bug I found some time ago, I thought I had reported it? Nevermind.

Do you mean that using the trackpad doesn't end with an integer zoom?

**Comment by iamvdo** [comment]
> Do you mean that using the trackpad doesn't end with an integer zoom?

Yes. As far as you started to pinch and/or scroll, zoom is decimal

**Comment by brunobesson** [comment]
Then maybe there is a way to force it to end with an integer value?

**Comment by brunobesson** [comment]
When I zoom in/out using my touch pad, the zoom info testing if one zoomed enough to compute data still displays integer values?

![image](https://user-images.githubusercontent.com/2234024/69331299-cc253c80-0c54-11ea-89a3-900747b2fb63.png)

**Comment by iamvdo** [comment]
>Then maybe there is a way to force it to end with an integer value?

Maybe. But on small screens, it may be a good option to have mid-level zoom to better cover a specific area

>When I zoom in/out using my touch pad, the zoom info testing if one zoomed enough to compute data still displays integer values?

Right now, yes. Because map only fires those zoom events. When the bug will be fixed, we will show decimal zooms (floored to one decimal), eg. 12.9

**Comment by iamvdo** [comment]
Oh, I recall your issue, it was https://github.com/c2corg/c2c_ui/pull/780#issuecomment-534241906

Did not understand at that time. Sorry

**Comment by iamvdo** [comment]
@cbeauchesne Any advice?
