### ISSUE TITLE
Add facebook metadata

### ISSUE THREAD

**Issue by mgerbaux** [c2corg/c2c_ui#915]
Add in header 
`<meta property="fb:pages" content="175865161596">` to improve facebook share display.
see https://forum.camptocamp.org/t/partage-de-documents-c2c-vers-les-reseaux-sociaux

**Comment by mgerbaux** [comment]
No picture or text are dislpayed when a document is shared on facebook

**Comment by brunobesson** [comment]
OK, but I don't know what is wrong with what I did...

**Comment by brunobesson** [comment]
Closing, replaced with #1762
