### ISSUE TITLE
Feature: RGPD: acceptation of google anaytics cookies

### ISSUE THREAD

**Issue by loicperrin** [c2corg/c2c_ui#942]
**Community discussion about this feature (mandatory)**
https://forum.camptocamp.org/t/rgpd-reglement-europeen-sur-la-protection-des-donnees/214608/72?u=loic_p

**Describe the solution you'd like**
Add a panel on which the user validates that he accepts cookies for google analytics. This panel should not appear anymore once he has accepted.
See for example: https://www.lagelinottebelledonne.fr/

**Comment by cbeauchesne** [comment]
@loicperrin you're fast. faster than me :)

**Comment by brunobesson** [comment]
Duplicate of #1138
