### ISSUE TITLE
Incorrect georef of outings

### ISSUE THREAD

**Issue by asaunier** [c2corg/c2c_ui#957]
When creating an outing, it may happen that users click on the map by mistake (eg. scrolling the page). This results in adding a georef to the outing that is totally incorrect.

An improvement must be found to avoid this. For instance by moving the map to its own section?

**Comment by momomaniac** [comment]
or asking user confirmation if outing too far from route location ? (Threshold to be determined)

**Comment by cbeauchesne** [comment]
or by not allowing users to change to georef of outings ?

**Comment by asaunier** [comment]
> by not allowing users to change the georef of outings ? 

I don't think that would make sense.
It's exactly the same problem than for routes: if no GPX track is loaded, the default point georef could be not very relevant. Being able to move it to some point (for instance an ice fall etc.) would be nice.

**Comment by AntoineMarnat** [comment]
> or asking user confirmation if outing too far from route location ? (Threshold to be determined)

I think it is the best solution. Threshold is not so easy to determine, in particular for the routes where only the summit is attached (access missing). And for outings associated to more than one route (when location is usefull and important).

Maybe 20km from any waypoint associated to or localisation of the routes ?

**Comment by AntoineMarnat** [comment]
> or asking user confirmation if outing too far from route location ? (Threshold to be determined)

Do we agree on that ? 

Completly incorrect georef of outings is a recurrent issue, and some outing may have not been detected. It would be a good enhancement that reduces the work of moderators.

**Comment by ataraxido** [comment]
I would like to suggest a different approach :

- display associated route search before (above) the map
- when a route is picked, pre-filling the outing georef with the one of the route ( like it's done for the title )
- remove the behavior that makes the georef filled when you click on the map
- add a button 'pick from the map' after (at the right) of the latitude field, on the same line

What do you think ?

**Comment by AntoineMarnat** [comment]
At the moment, after one click on the map to set the georef, you can then draw a gps track. 

Your idea seems good to me, I suggest that we also add a button "draw on the map" next to "upload a gpx file". This way, there is no (mis)behaviour when you click on the map without activating a button.

**Comment by ataraxido** [comment]
Should we ask for a community approval ?

**Comment by cbeauchesne** [comment]
IMO, no, it's not a fundamental change of UX.

**Comment by ataraxido** [comment]
Maybe then the approval of people involved in this issue ?

**Comment by ataraxido** [comment]
Working on it I have a question : isn't this current map behavior a problem when adding a route too ?

**Comment by cbeauchesne** [comment]
yes, I guess so. @asaunier WDYT ?

**Comment by AntoineMarnat** [comment]
Yes, in theory the problem is the same. In practice, I do not remember any georef obvious mistake at the creation of a route in the past years. Probably, users that take the step to create a route are familiar enough with the interface. 

_However_, I suggest that the interface looks as similar as possible concerning map management between outings and routes.

**Bonus:** at the moment, when the georef is on the gps track it is a pain to move it: you most likely drag the gps track instead. If there are two buttons "place on map" and "draw the track" that can't simultaneously be activated, you solve this issue as well !

**Comment by cbeauchesne** [comment]
It'll be fixed by #1937
