### ISSUE TITLE
Bug: side effects of window resize

### ISSUE THREAD

**Issue by momomaniac** [c2corg/c2c_ui#958]
Several strange effects may happen while resizing the window
A) BBOX: bbox not persistant
B) display modes with poor usability (if list view active in desktop view, no results are shown in 

explanation: some problems are caused by switching between mobile and desktop mode via window size

**To Reproduce**
A - BBOX:
1. go to outings list
2. select view 'maps+results'
3. activate 'show only results on map'
4. change aspect ratio of window so that map aspect ratio changes
5. observe that results have changed

B - view modes:
1. go to outings list
2. resize window to desktop or tablet size (width > 768px)
3. select mode unavailable on mobile (list view or map+results view)
4. resize window to format smaller than mobile size (width < 768px)
5. bug: no results are shown

**Expected behavior**
Window resize is expected to be transparent (conserve previous mode, but show results in compatible/fallback mode without user actions)

**Screenshots**

**Desktop (please complete the following information):**
 - Device: [e.g. PC, iPhone6]
 - OS: [e.g. Windows, Mac]

**Additional context**

**Comment by cbeauchesne** [comment]
a) the bbox parameter should reflect precisely the visible portion of the map, as it filters document visible on it, so it's on purpose. But I understand the weird sensation on resize.
b) Agree. It should automatically swith to card mode when you reduce the size up to mobile view.
