### ISSUE TITLE
Bug: inconsistent text alignment in document cards

### ISSUE THREAD

**Issue by momomaniac** [c2corg/c2c_ui#959]
**Describe the bug**
different data of a document are spread along the card and same data category is found at different positions for different documents.
Example: 
- max_altitude is centered if the document contains rating and max altitude and height difference
- max_altitude is right aligned if the document contains only rating and max altitude

**To Reproduce**
1. Go to outings
2. display mode document/card view
3. Find several documents with (different) missing data items (for example missing height difference)
4. see that data is not always aligned the same way
example:
https://www.camptocamp.org/outings?oalt=0,6350&bbox=-485696,4590279,1710798,6791665&act=snow_ice_mixed&grat=F,ED-&odif=0,5250
should yield 2 documents `Cime de l'Agnelière - Cime de Juisse - Cime du Pisset` and `Chaînon des Guides - Chainon des Guides, Legramusas International`
first card has max_alititude (2700m) centered second has max_alt right aligned

**Expected behavior**
Display max_altitude (and other data) always at the same position inside document card

**Screenshots**
![image](https://user-images.githubusercontent.com/57792650/71645796-f0f1e280-2cdd-11ea-8527-5f441d74d749.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Linux Kubuntu
 - Browser Vivaldi 2.9.1705.41

**Additional context**

**Comment by cbeauchesne** [comment]
Agree, an element should be at the same location. Quite easy to fix, simply add an empty `span` if value is missing.
