### ISSUE TITLE
Bug: "heart" donate button for forum

### ISSUE THREAD

**Issue by AntoineMarnat** [c2corg/c2c_ui#985]
A heart appeared next to Tweeter and Facebook items, at the bottom of the left menu colomn. It links to helloasso for a donation. 

This is great, however it is only available when browsing the topoguide. It would be good to also have it when we are on the forum, which is not the case.

**Comment by cbeauchesne** [comment]
It can be done only by discourse admins. I closed the issue here, I've asked on the forum,
